apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
  namespace: openchamber
spec:
  secretName: web-tls-cert
  dnsNames:
    - openchamber.mtaku3.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
