---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-sha-plugin-secret
  namespace: argocd
spec:
  encryptedData:
    plugin-token: AgBDfuxTSk3Fab3XKbMW2lGkvGk6uYNTr/fVX01GophZ8SFEROAJ+NiU9KM86WhB9ysjQ9Q+eSO8Au/qXWdQMhKlqV662HovFyQq5nRvfsrj3rNgqXULNuRFRYMi7r33Tkmz/Ve76NpoD6/FC2Bg4G75qIgWg0OAzYQiaXWIhPpj5bZWaYbU10X8pV5l8XKIHOkKhw4Xz3xtrnQ17yJ/qqoelD0JmHutaUlCWvfSDm31BnWKb8tJV73KrqRr5/oXnCPNVKuiWSngRUriOadQ3Kl++TNtYSh38/jeKg0RzQ3V2rO3s7v4MHktIZ/Ovz+fx9Q3qwADeY36qb/l/8PV/YI6SvJJV5WWiovwpjVrlRaGHErleDnHAsIhvTQnRjDHSnXrmGCWzulAL+9WY7cj5EV8DDe8J8JSRTZPMcLEw1lCv8I8cin1YnEvw1xRZoZFf0gRxpq9oSuAXLDVWHAitITyGRJ856MeYblyySRDxWsM6XjESosEoIE7ZPIkAmAPS9gxC5gfUyA6mKd2NVS6XSKULkvLzG3itmboEUiOXbInZzH6KKxG+2xnU4mKFa+d/+o6nrSq0b6XOELkTpquxkIDcy/UCqyWBCkI9UJEoP/9SiQbscUzhhKARVJNpwItvYcuAQrEuQt8FYCefklpLykAxL3wjKPwf6IXiT1GZeOteTiikmhkK6rOr2K0t8EsZD53BPaBXpLijQNSvslnlgjYR+T3fOHDm8JopJaoZEmvzgGYQBRpGO5m18F3ma6gSGbkVaQHav5l8hrn7Y0TK96K
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: github-sha-plugin-secret
      namespace: argocd
