apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-tls
  namespace: coder
spec:
  secretName: coder-tls-cert
  dnsNames:
    - coder.mtaku3.com
    - "*.coder.mtaku3.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
