---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-db-url
  namespace: coder
spec:
  encryptedData:
    url: AgAeFP4bDQG+dod/FyU3i+xkAQZoshvcHLwoYBAwOI8C653PggWq7LW4nW/y1iw/Scc7nWLmWJ18jt0/FZRXEEDf14e9O/JtoTcltVtYz5eKyEyyUe2zKJNYh39Aaq+iMlm5ziz154gXkAh3uwBfX4pkNphahZe1WdNLacqv470amWkWkgbw5i+0oc3LVGhUIZDFz9MX7yxc7HEcyE/FCzM64OOghybJA+I7qb8ZuXsP5DQGS/fWZ71STHktB+HaFy3AxOPsoA1FitM2GWwuh4UeOxg7/NJR9d8S0e1bQlShw5c/JuQIT6ifk99AJ0NE9nG5CtFOEeZzT/o1EUKSL5pkTevR8lmpep1QPxT8lgr+hAk0aE91LNgE1TVROVKnDAHkWXBGCdLCDp1CXyh4DSkCT1Z5MSXoxjUDInMubwaqdoQmyWKBjvBlg8SqVK8z0xUOrEde6jG+CX36ppnyiU1i7XB2DhWRei/QUDKGTfZzj6lEg6raJRKyXw+nfcZNzno3cVyOcPfeIRPYMWwDnHpYLwNajNQuxrMysvPFrTwR0TgXr/GS5BbYGOH5qDR7DsGClmvVpk/i072gpXgO8iyWxi3Z+up9mGEU0eoPhTBErSfu63gYU1AJmN/pVY3mcy54TEZGALBydvYQlJcsn1Bg8r5RCiJCumSVUmN4kdQOjL/jaRty7m8poYUPhprR5lNI11nDNATwuap6QzG5M2Ga8o3fH1K+QXnV+24PynPXkd9U2DgeUp8Ih3cAmFzgB95329/EErzqtUDieuPdcLh3c13qa1+Zppnf6MzW9zxup3R5OCqPM3aOxu7m
  template:
    metadata:
      name: coder-db-url
      namespace: coder
