---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-postgres-auth
  namespace: coder
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCEdbyEV62/RhQkwtQoKfek3vLgrmvMqGHsCG/m3hQ3bwlXKEky4Pb+O6pAIBblrRSPxm0HOjXJrCNjC+dNyPy3gJsNfCUwm9TF0AKTw8JydSsBJXEcZzndBzrUzu5MDc146OP4LkC0WyV1Wf4/3eD4cIVjzqKqjO+8a5Y+UjT9VcUx9QwJ6QmfjLrgjwx0PVztq4QmMKlysHFAO2Zf/u5URxzh7mChFkqbyA+fTBZ5pJmlQDSqhSdvcIBzsZjwe84mhT9Pc3PZwH2/3F5xp3xbnQTpXslr3v9vu6QXNjIbpeARINhA4o2ISeCPuFU8yXTTGY+3k7izHllyZfLiVCFCDHuw5+hv6alchqZp/ZgBVlmT3/Zan6XUiDqRq3ku2XQmEvdVSdS/X7jjKjp3jBIpxK8my8pGujDu1rLQvTzPBkCbo7iOzaRmfW+MEs/p/9gQ7mM8rwNpB8/1JaXOyhUNxUMkJ+K2z+kO39YHbGK75fJAdrv7ura+cZJaesZutCaXeXg8BpArlfgNhhedOK/yVs1mMFfsmyQfmC/KyVuM/MyHSlsne+T5asVdAXtTqj4j53eQIL6tyQ3JqhXB+38tBSxPiQkH1bz33MZuCPLMJWxos/XalFz/ADfLp2OBs+3cyrSm9JsV+i4YU7c8+ZGsoFLjcPqSsdlgzee55732YcPNtonGHmNp1lx4ExDV06xyoyd7bUAXOc9FQvMJDzYF3NjIvjfDFoLCE9UOh3fLhQ==
  template:
    metadata:
      name: coder-postgres-auth
      namespace: coder
    type: Opaque
