apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: happy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtaku3/homelab-manifest.git
    targetRevision: HEAD
    path: dev/happy
    plugin:
      name: homelab-manifest-build
  destination:
    server: https://kubernetes.default.svc
    namespace: happy
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.status
        - .spec.volumeClaimTemplates[]?.apiVersion
        - .spec.volumeClaimTemplates[]?.kind
        - .spec.volumeClaimTemplates[].spec.volumeMode
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ForceConflicts=true
      - RespectIgnoreDifferences=true
