apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hindsight
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  source:
    repoURL: https://github.com/mtaku3/homelab-manifest.git
    targetRevision: HEAD
    path: dev/hindsight
    plugin:
      name: homelab-manifest-build
  destination:
    server: https://kubernetes.default.svc
    namespace: hindsight
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ForceConflicts=true
