resources:
  - argocd.yaml
  - cert-manager.yaml
  - cli-proxy-api.yaml
  - external-dns.yaml
  - gitlab.yaml
  - hindsight.yaml
  - mfsm.yaml
  - open-webui.yaml
  - openscience.yaml
  - paseo.yaml
  - piraeus-datastore.yaml
  - presenton.yaml
  - sealed-secrets.yaml
  - traefik.yaml
  - victoria-metrics.yaml
