resources:
  - argocd.yaml
  - cert-manager.yaml
  - cloudcli.yaml
  - external-dns.yaml
  - gitlab.yaml
  - loxilb.yaml
  - open-webui.yaml
  - piraeus-datastore.yaml
  - sealed-secrets.yaml
  - traefik.yaml
  - victoria-metrics.yaml
