apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piraeus-datastore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mtaku3/homelab-manifest.git
    targetRevision: HEAD
    path: dev/piraeus-datastore
    plugin:
      name: homelab-manifest-build
  destination:
    server: https://kubernetes.default.svc
    namespace: piraeus-datastore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ForceConflicts=true
