---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgAxzyvxRiWEa8kimJ8cRM7jgp5IwNGpvVdnMENVkO961pph7vRY7ojwfKgdf5pawiY5g5ZOWP70Z4dwDUaV2XTiY6a/N2ZOw9sKDNKuX+6rWo5zDuURcM07Gem7SOq2b97ogMDTxI8OU/cADWLzqXDw7iU1c01w6pepWcE4YePRq2Fn+lltEo5l3pYmlN6E/tD8RV5PzUR1J7Tfgbb2EaFize3290MwmcpDzOr65QWeALnzhjPHSYjBMIQFqDGUiK1X6UgChBMIehtfQeqNGjt3HwV2gVkmSm7Z7iqKN2WbKoiDdFtZ9OpSKl6FmBual1j+ErH5IoAcq5utRNsLF82aGwz7xRsCKvR+AaPGCcIfH69Yj9TuU5MfMdwcBNtuAmb6wVkFnjtAGuYXdJx2Nq9c51xiOdWjTIKrOBuIIujd3h/ziBpaEkD5MohVrdZH2RYGfx62fOUSX4fZJT9f6gkWbvaA+WY45L2EIxs7PXS688wxkUUBAx/rvhv5dsaUhQENbaCtI7LrVfM5efnxOUsPkBS2eh4iy4+znrbcDH0F0Mb6G/gGiUusf9bCgSX0yk4RmeqKi94dbL2kGwGkI4IMQIEbri41hBqEHG75Im0eogUpmYtA9M6nUKqtwxUFyQsjW64cEf05Cz/Z8H+6EgBoop40V+Uigyhrg8juRxPksGsCBztPsQMK9XyRq/dfNAeJF7CTZotisXntMIR/KaIsv1EEVVGY4/fxcWSPhI22Eft3C/mK2WTK
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
    type: Opaque
