---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgCBtse5wEAzmUliZsj1LikgoDayb1IsZfHgCMlX2KdmwLc3u6AXzT8EXBfY0x+yE9MoG8146U6KkOoL6jZw2gXg0Ff54KVKP4K2X30ri0WbKmTVm/8epRKJtmxfM6H+l062TUCXAA93oEMqq/CAgqSgBsnupqX6vzZICFJU0m1ugTCTJd7pYOW6JO2jBGGDSbdEhjvojtv4EcyBm+QJG5Fju2UxU30RBMbtYwCZn7mGHduEdKGo6yGonVYw/cGebqzR47Z1JpPF99SsruluPSO7SzUNcLpiRgTpLQOkg4QKvVo0dSl/W3Xexp9Hq9RiqMYqiaA5CPL4Lp60Qgm5qvvXnXzfUQKKE5QwmrtnwY1lsE/4IoeGiDc8AY4MLfHD/ZSRiCGRTSQT8rRw4gwOiwCSohe9W0vozhrwPHDYePl1dUF/e1n0CTXkWbyWCzZesf8kTlEyAQmWKOltqZiv6jD3t3nZCEg7euD3lYNJATSM2jYtAoqOzTHRK1s+R276oKFd4MdV5KAd7GigHB/ubqLeQoToIqnK2a66fzswWcjqfgMSMVJS/pU/oPE21NnlTO+dC6NnzWwaxyBe+77L+oDTUiqqhmDJOKxTlsXZg/n48+QHyDSdPCLkmHJvsPVp9Cr7eCGYM93xcWVGrokhYdeZVhCcEPlc4joAZqtT0FVLZCH/Gv1rAs/Uh3bfqsZ7B/za9PnZ1iwc25WfXyKY4eMI9TTRxlTD2akZTicKI4LfNQ9tUD4xSNGY
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: external-dns
    type: Opaque
