provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

sources:
  - traefik-proxy

extraArgs:
  - "--default-targets=202.215.58.76"
