---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: palworld
  namespace: default
spec:
  encryptedData:
    admin-password: AgCFjDiaWkrUX2OrNdI0euPky0kqKhPut+1scwKm1+8RgHOHU6K54jA3TvlAkPdofe5fbtP3Cj67TECIKfj/jfqRuLhzYiS+512f1EA47iqnwafKd3RZ/wFS4Mt4XE4vjcS0YnVQEGLEM2sNV5IyF/xJwAB0IneFEQDILUsOArxQ+XrPIzNQA/AW8Zgwfy6CwEykO2GYwnIiyul61L+j5gL1XIFFtcCpkFiIkdB5MmNgBdZ93HZdlIn+zxiXdYj8JxWBaAo4FkNPr/zgLHn+DbfaZr6mUX5kAPBk+Xzojfu0SbD2LQbW+DPp27tv8HDG1GILOBUfROV0TyiAsj8xIJaQ4mdY5nwximgiuQuWjmWnu7qJkbVLVNvuYHFJ+nNO73+zujt1f1oAhG7r0U5C1J+7YJHybXMVbdmCQ1+h6gilre0LuAjXFXwNfisf8DnAs9Ej6XlARrNKM/MXyk8g8M0yAcsIA73iwVowU1OiXFsJIPg/UmuBXvjecPPPbY9+SkXhkvHKwbHS4nHrOfcBNa7t8gyFA+QklbeheeMtDvc5P0669OWSAJSVS2KUOoY/CKHdQk6qYGyJ3Er1uhpNsSQJUsbla+WcdY66gs1EN7evCLo7Afa1mOeoM+xWTa3wxV85VJo4XFrQJFV2i1wR4IXHg9tdO5j1R82u3kjgsBPt2EZ7JPsuzbi1cYjjzWnw86fd8Qhv6agIP7cx7EenaFbNwNZ/GPM9hJxZmCsI2B1Eag==
    server-password: AgCB6CMfKvrvxaPybHs/cXUAn4rTjswBDG1wkeXh6R6eXfKcDSa/c3Oeu/SDFefnq1G3bzM/yL3YxKab3UQQeSSXJ/ub6TmPC7LxsXjTeCMiDA3wi+ZsjRJcuFa1PU+rSb5ZBUpbZJPsqXDZRvnomXcgGa71aO2CpXnftvjYiF5Cz/0+AplTmHI8C5MZnFcsRb+jId85cOW3QcFo+li9H1sJ7E5S5eyKjuBULPVN/jWrsFqJGAL5XnY8u43Wr3u/CBnEXNmnBJ4UMTgQmQFJGdBZ7nR2ry/9vrnRxO1fi4hVQi2Jb4iSxhGzeyrKhUtlyUEV62t2t7K+CMrOR7D7FFl1eudX5EAz65UVJDQwuZiiqwf1zRh546Y2i4EEoTG4Kt/IehEmF3ldycuB5xpnHkEnVk/x93ylnU/W3GlLlWh7vLtAZ2xiXjsORIxXToLGFkzdwyQkqng6UUqFjwcIHMub8DDP5dYn+K7kEY5N/KVcYNM/HKBZpaX9Fn+c5GxqIeCRjz85Dtg+I1sy+9UqIfbnimE8MEp50Q3iw1vQfPIfT5ToKKGZ35RGBei/ez01/4XnZd1CU+uMypFF5IjDyRNDSk6IunsiKjacLpeV6Xv35uIFss6eZt03H8UN6VyhCKVOX1LE93UFl+gvx0cOnjwI/ii7FJMeMijZ8HsRc/kLTh5y3gf6YlIQZ9x99/f8GyXSZ+q7ASSy5RlKIO2zw2PIQ4Frm/czHeKhOPjQqW7QUA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: palworld
      name: palworld
      namespace: default
