---
# Source: loki/templates/runtime-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-runtime
  namespace: default
  labels:
    helm.sh/chart: loki-6.31.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "3.5.1"
data:
  runtime-config.yaml: |
    {}
