---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki
  namespace: default
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCJ55tj6Klf5DjNWQ3g/iBZu3d8h570tJbclRcA4nVVfCLY0sDxyAEN06wuCGZVPGiJd8Q0u7GI/WgT0BiYNS/7K0y13qzVaQyuswZcmcSpTIskuZj3B3VFskOwBRT9eaeJ2WJ9cYh9Fgrco+v4UKXM7RDlabwAiKvd64uMIy/QjEVnQY7c0lYJ9Op8m+hUdey4bdShOiFesGELv0827yATvfPpPjEWSWo58dWyZNQL8k14YJ29UHpXruWC1Qk93C2NdoKToYmM9cME1nJjCgZ7urWWY2iGt4scz82UA/x08Aklepr4hY6NdRe3ds32lBu8sj4vNB+ztX9TESWifRtcit9Ig6Ub50gyRGEe4p5zKfs+8u+TizdNJyv9ZB2Btao+dVvIUP/hCxLEeIuAHTst7Iu6JKaUHkdMuyr33Ei1floWekNcJZZvABU2qSra70m2HSDHO2NbQgLFCYbZ1hgapHtBjs3y2tUByfpazbMSSzDOoI9B0Zap5k5cRj2h87z1k2umxP4Z0awHAqAu13OezzGsXr0zPgvl2f48AuqDVz8HGFN+KZNoBbt8gX51lYOxM4Klctgi0pn4k/Y16HY3oWe3B1KBu3/N6swX05gj6xILaoPy9exA/65jcSlGB3k/hBUImR9S8cP0WSZthYdmanACXMWKGWp0u6t7Gnfqzs+t5vrEm73ZXbHlgDcC//pH5pvNqZjfUys=
    MINIO_SECRET_KEY: AgAi8C6P/AruGP99AKm1E6GYpIRettw2IMHSOeUs3QhOm6vdTj6flif7ZzQham4Lnu+nFTUmIcC4Sbzz4x/1Yt6FLMJwt1aUUfDzqQW2LejybHlcDWZCTzqo+RYQ7fvQF0KiN0GuTDFPWBaONjziQpx4Yj8V28lFCgzHFiLPfrbfxhZPpCZLPQhX7PPf/mcbnyLiZ2crJ4b8y+MzR0gxqQzMt1z9lyWB/B9afYyiOO1gOnJfhZmBxbr4v1VFTsmGbPR9Kwku/zD6Yv7qoM8j3EEL+F1W7dYYUfsAkkOCddse951ha1lv2TUHWTpMFPO0B3Kpd75Xpzp8THjXxAY9M9CfIcDTK2FHY0sUOdkKbEiXHgx3O5t0tt2BtKanhC6f6r+Vn5j4swGV6HXZPmjy2gJmyD8xcQyRZAKTGwa4Fia4Tl346n9b7jU46xxJfZvcVLAcpFNPwK1BbAfIA31fUBhP0/B3GKIuHwJKppUM0zdHs40/oz/qcUhwHjt5aWMRMzJWEMsgt+6H2sJ4HFvW8WiELOyUz+nKWUIu7ft/Y3STDu0YkJANg0CTAMKadR0u7lkm3rR//lnvi8a+a9BpOvCOhkOHZPBsGlDpiAcznYckzpYAIa2nBS56UMGDy2+4oJuVoBzpC6MwP+YqzXtiQ1W7zqHKyIkVclVAlmj4yOxxKHaMtBwzn9h3Kk1ePg08W9D2Nq6OroGo0i31KKqBoGrWztSL/8yHT4BtsvROaGVg5VwHerIja65/
  template:
    metadata:
      creationTimestamp: null
      name: loki
      namespace: default
