apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application.yaml
- console/deployment.yaml
- console/networkpolicy.yaml
- console/pdb.yaml
- console/service.yaml
- console/certificate.yaml
- console/ingressroute.yaml
- networkpolicy.yaml
- pdb.yaml
- prometheusrule.yaml
- pvc.yaml
- secrets.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml
