---
# Source: minio/templates/prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: objectstorage-minio
  namespace: "default"
  labels:
    app.kubernetes.io/instance: objectstorage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2025.6.13
    helm.sh/chart: minio-17.0.11
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: minio
spec:
  groups:
  - name: objectstorage-minio
    rules:
      []
