---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: objectstorage-minio
  namespace: default
spec:
  encryptedData:
    root-password: AgAYXwR+JMNIrNcAyM9Hd8Z7Yj84rJPaCHnX5J33G0rmSry0JvNTpaKdkOpsRCe33AAUUhT9jE0Jgv18n02DTJtHZspZRuHGmXESM+VmBR554xWKIqZsXFtS2toGgFaCyZg9aLI2sFgdUOtlFUooe/XjaF8rarCzp5+af2BPbnj3/YWv26QB82rlpIVypEfaeVCbRptY7BzYxmnWZ+MMXYKFoIiRxm0xERaWpxpTx4KfP1Td+GqQ6tb2cDIMy9IOBcva31Znb8xRtdYLu54qjUWXliT2pjc9OSAHJ3H8TMu49sFrgcIASuxYNcz0KMctf8yflMbUokM6+doOhAHlRn31oepAVsMPJSIFX6HXNHgc5X1jL3Z/mTtHr8w2QPB/qKSitWBpgAl6g677vdE2aXrCi2sx3r9vEtvjvBt6QLeNcGnsgiVbkg1Z/2nCPsKt/8hLO9JkJl/dg3ui82Jb5T/+a8r724gnKrqiK9sA9yvYB+mhnL+fR9VHOnF5jmI3ueWp8Zx/gqJNKbnHkG8Q1koy7ZDAPYrhctGt8YIezD2SwJRdEQPRFM+HhA11Wzp6lDX/bN9xexGdqunnH7QwuCUeqOzjufZwD1SSOEXsnLyXe3y+n9A+jALxm9coGO1WAIN2QYiOufOIeLNZvEkuLHCTT898OwLHzP215RTWZSs9AD6DGOJrpIAMdYTcQHbW6qoVq9VS+/qkFNo2wp36IPe6mTPx7V+sKMYDELh9kQT4Jw==
    root-user: AgC1r0pXXupDjFAViipXkfGO8WxOJAGpwI++zErOkpLDLTTsuJ7SGibv7Xy2ZWvxw4mT86clesgpL1/0QtYKmcLZJeyT2ES9kTwZ0YerKmAanyCMgyr5m/EkCpBY0oytq+Ww9z5GVtdurO+uDuhOeOkuv2gPabGtAxkOYmfAQHUiuXlWVirSQD/bd0T7L7y6xCkmySKtvgsIpCGagliKoY8QuCscSCL9bF529BBoSWfphkJpAi34VbgzpgIVaXZukaM8EciHt5fj94l+mSAPtsArd+31iq8MQ8BXNb8Nx/WqbEx2bzE33Al1173ieDN+Y8RRo68n1NwQFUP3d18n1LrJw0PoiMUH20xXnXTQDzRGhPCi9HvRjoFXnuvdP8Nun0oNwrDvOjiAr88QcFhqhmdFdqMOlp8K3BWWFFbmimFHJFcuNTPmPilNigPXgNjbj9KO63xE8VgjU/O9fGKplpbUNotRy0TkEPeULM7xahRfrJzvALL4pZNPVz8G8eZuTf4dDg/I42RJa2fp8KnIrX+BseFg17jP4E9iFVs0JVhjnsNi0qGv9fZOBP1Cj+efa/G71ULxDYcj7crxjmTAsZu9uIwc/AV5vptalcKUDMXUZTwVWu2OIAxWFb8gssHM3zZFGuVdp39nq8DZ96raxW3VgEwd2dA4e4fI8G4KdlIb1ZJ8cgOn7JH6gAihCrRcVbQ2RqiPCNw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: minio
        app.kubernetes.io/instance: objectstorage
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: minio
        app.kubernetes.io/part-of: minio
        app.kubernetes.io/version: 2025.6.13
        helm.sh/chart: minio-17.0.11
      name: objectstorage-minio
      namespace: default
    type: Opaque
