---
# Source: minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectstorage-minio
  namespace: "default"
  labels:
    app.kubernetes.io/instance: objectstorage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2025.6.13
    helm.sh/chart: minio-17.0.11
    app.kubernetes.io/part-of: minio
automountServiceAccountToken: false
secrets:
  - name: objectstorage-minio
