apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/name: minecraft
  annotations:
spec:
  externalIPs:
    - 202.215.58.76
    - 192.168.10.2
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
  selector:
    app.kubernetes.io/name: minecraft
