---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: hindsight
spec:
  encryptedData:
    .dockerconfigjson: AgDijVuewn3fvBqZ4vwAWrS5jCZfGWrAgnoL3RwRAJQbRl47U11yC6e1JyKOYCLzEe5dDavg4BE8oFPzHv2V2G2v1NqGG24c+keWP+c6F/DrZWp24FcYiugZJGbFgz8RjgMrKYKyZ/+tbzv/AbGLysOON9RPPARVCL68/P1eM0+Qwwhwib0pRTvH73oB18plcRv1FN3F3yAcIDcs6dcJAFgj+L5/CAUrG7YggcWqZ9etXJvL02NWCdT04zEMZ9AFC8fT6OwkGIfKJz79ScLL9CTB5EKAGj3gZ9O+4P3qflKt1TkqypkXGhNtCVcGIdNsj1AJVH6W1dhhXmn/3J+Jc7AD/bLf5TFPnozkW5+OK0YRygd0sfwn+Ir3vw2/4yEE2XI1HVNdIf9Tewn61H0jXSZID6F8gLRG5QF6RyLRWJeqCgRkaXHkbGVt+U69dNlza/bLLAgG5+2tUdy+OO9Y0dWXTUcOX/P/sbMUFsUa2HX9Opsnx4bKrq92mAxmEPLuVpK7ct3B28+quQpcidrQV8lxyDmPHZuFAE+BpMjLt7IeTQXvLgOhJGtKSkJlZ9SBuXGTpYyuQbFfpkLJzTBIW+7DiZDguROFqZ1339N5yXfHhIfAUn8E8NWmffHBY4J7Ep5A3RiVPsvkUhTEfeSdl/bzs09BdtdYnRaCxKOWnhc/TlSLDk1+twFwZ2T/I5FKCoMqJ8NQ6x1kTQnUMN3/m2Ur0LWovm4ghhHX1L15cpxAf0/mC8IB6oJ3Gb7xE4MY9Te1l3psI84JHU85qnDnm04zKaSmRPc4Hpd6MNoPWHqRFke6n/IcQ5ujf/6IWwG/6msiidVJxmW2M8LYCekzu+PC8O1eCBGVsR+FR10Qvueewnydp7oOD9EAh9A2nY01QJAXi2KoJPJK8QDekreTcjmd90hj3BZydQjBhf8=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: hindsight
    type: kubernetes.io/dockerconfigjson
