---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: presenton-llm
  namespace: presenton
spec:
  encryptedData:
    CUSTOM_LLM_API_KEY: AgB9YFMX8j27MRR4SUmU0GvFPiuK/wx6azRpjSNaVcOuZB0v8KkF0PcuynblcDBr58aFFc5NXTpibIXWH5p0MVVA6Zw+zcb6IlRIBwOnYuRtv9lMVCBBRx0bWiRX2N3+NkDgv5kqeyV7kURQ3EgplNxa3erV+M51nizY4AX1vQ6L8wflxk+Uc5BgWC0TAPELILXlanHZReVkyAWYD0O6+7WEEMsjTfxSymZimUUi/G5AkkoORZCRIGUQNZANH6D6UkH61fOOlgv/bgNljglIduSg4Q82DZGmuAeyGCFko8trcoDX4Et/SM861mATkSXJ9QWwX6tro7jcPZwcrgZOqe2LViigbnb7Xs9ltIPfTpWZ61BQFBJCQvRmAy0U7xZavTq+cXyXla41Rpcs/qBAjV4WWeIxj+Sb9wf6zXrKKQguBj0tkfNSwUCEwK+CLuJ/cCVWrSKE7gmBlqu0c8uKJUXLoTXtb+6tnelaQ6TzrqL6ig4Ku3W0bXJk96dOK9thtJBmUpEmdBm00TOkvO6WdvChQUC9sHoQWIJQVJf/qjWLzot5+REY+nG2WbpCBEj3e3Axpr/MmQQBSUArafi+ye5QHVIYwRwKyF82WyoEuKdFC+td5erMS8YN6MWVIniSX2di1cwTa7/QMSJHO+Fis1zgdmdova/Q83gE59/xtP4v5TuCnVEZ2qiREQXk4mb17rpMMGsg5h3ATjw6QTHnW36fFm73PbF7qTYFGd/TMu0U7PRyBpTkiKof2XXnhrQvOdrnIhk=
  template:
    metadata:
      name: presenton-llm
      namespace: presenton
