---
# Source: loki/templates/backend/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-loki-clusterrolebinding
  labels:
    helm.sh/chart: loki-6.31.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "3.5.1"
subjects:
  - kind: ServiceAccount
    name: loki
    namespace: default
roleRef:
  kind: ClusterRole
  name: monitoring-loki-clusterrole
  apiGroup: rbac.authorization.k8s.io
