apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
  namespace: happy
spec:
  secretName: web-tls-cert
  dnsNames:
    - happy.mtaku3.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
