---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: happy-postgres-auth
  namespace: happy
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAV15+UUUseQ5Pq6SzzI3xKz3td9t/6AxhOwfUU8i2QKCGiUZKfflg2S+UNl5jVKKJRIWQOtd3MzSc00Q1M3i3dhLRrcSr/lNkx2wsCaaI0nvEOV1elufH8XPMWTago9jijIkC4Mun+qMUnHVcuqxywRTeLKgdBhH18teq7z6gZOEX3ix67LnCeLpKCwF1RE/wWFzCF2LEsUetyZphCN7BaYpkS/OgVLzV3KdqRgu0PLsLZFRTirN+gsLP/2zNMcMWDAONWFFqoLWm7MOCxY+TWAQpVBBtG4ruWjeuujakcT4clRvlXcRxQMvsW8OxV9/UZKehaBr7kZKMg0s2Ih81zu/xsQxygWxTPh9yoJo+rogyL1Syo7t801XZvJ5ORlorFXzgv43OuAM7rz1JfjCm9VNLUQAMUTzsDbAJb0DIrSVEG5eFX6zlZieJ9LZXyRrAw/ZQthRc3tkSlfHXeva1tS8Kg2WBTmc4ZN+u0sR+PxQiWMy4a6eTnic3emoAA369dIDPys5ZW5d9Tn67Y5S+FSG2vmJNaQejaobQVvz+OilYkATHzElZqDeIC6gycmNWfRhNLs6kPM+uG0CZhsTFPtRNR0gjK0JyCmomxd9GhMUOaQewGp+0f3QmNekShbhcsywwr+cB2RUxcseXREEgsOCasQHNjiYDjalDIfegB6M2ktVu310EZ2GiPm9u+D7eL1sFkRf2eeCkKhKJICNi/h9uFCsFdLckvDIZ6GfWzt74qjusI5bZr
  template:
    metadata:
      name: happy-postgres-auth
      namespace: happy
    type: Opaque
