---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: happy-secret
  namespace: happy
spec:
  encryptedData:
    HANDY_MASTER_SECRET: AgCbbIRQ7bR7wi7fraQHZOmJKUXi7RrEYd/lKeVoocNLiMxZGD1xZl5CboLExg8ef92WaA7zaKWkSSobTfJbFuTDXIOK10XcG7jUunXrGpGnjeeBMM/RYwJLj+MWCek4YfKDVYuNPxjPkXDKxCnIyA9UJPkgGpdjgkijeVYhwsLwTI5OKo53YE1Hiw/D1MOO17aRYZbNnLE4SWC/+A/qluU41f381bNzJ0e2WS7xkauPbnZl3Dw/r03WA3lOXt+2poWhog2P+pqIA7JWTiQi5WEmyrf4871sSYkwPa5emanGp824iep+1Fzrh4Vgg+RblzQ6sUInYlhuGsFjKvlFFTRxFOlbWNYdB0geHd4qCuhswTCTVRJyoYXd6gBIJ7OoKLz67Vs0CEIPYRFbrPOumkIJ7UJbCeVZBp0bGwj6U9OeEJnB53m7Kp6zqTBvFRJmPS2JPayWXl8BZV2LsgZ64u9RklxzTa4a5RRIAsm5QYOx0QCAE1PXSbHUZNe6QMu5wtvDRCqmrNiRUnDnV4iAl8QCL5BGey/KN9bMHpuClBU3ih2qZ0FVC0Tl3bLJLlOlRD4GVlq6r3h7mW0kJiOxFjNFMCoy3QjN+XMcPSlyQuY4MhJaI4qF/rQ2bE2a5C4yhR8zv2E5LIOKHU0HAoDO4nZ6EL0kzNet8ZA/n7LFIhWeeDSVcLj9l5JJ299oEkbF/zpkgRFnHUdZVyq06Lrktf6k2Hv6u8LVXODicqeH9tycaRNNsPorDAEvUiKPngN9f29rqWKIxS1RFoxT5xG3SwwR
    POSTGRES_PASSWORD: AgAivYkQ6Iaxyp+yqqMm3j3483dPYXRHt5eKPTR5ETJfvvrfKUCbbkOhR0OnQEwJASbPTohvD+9cmQXmwxDYUtmBapLpXLkMGvMYQWkZa1qUPaAcODFMvPWg1rMcRpADIbfiVulwNvOhff+3Wcdrn+VnQt1HxE/L0CjRrBLuDA9OOeBAYdwMgAXpEzYZhiEJ+no/Fe0dKoiZWyVsy2qXQxND722BzIICeNM1JZI3yTTu7gXtGq5lcusf4URMt1DOtbqVbWQWzxYJmELtKi5Net0IYs2YJ8OoJVZ7C7Wvh20BJLL4lILKxQHrSWD9/gw6gJL9YvINhMVBYmUj6p9Fw6nfQeVwj2yPE08RzbjkThmR9h2rslUFdVaeB5a8ox0O3fwwYP5JuAwALaSjQfRPHRHkOvJd2vMv+0NDQcr84jREGsYEg+G1LDX01rZrNx//Yl5Zwq8IOw8CILpjVJ4u+3xjGMeXebrUKm981IqPZ9Wbbhofd2EeLX8Hmp8rZe7dhgFscxR4PY2C53s0Gk1WMvrGXi2wUqfQOjAzjMz+QtSHqVk1kEKxNHtnm4sC9j3dVJHJLjSYExvXv4/yJB9yuqz5aSYcabCTX6YZhCqn1Pm7pHjEca3pt5wFRa1ALf7cvain6/eRi6NGl/eTW6Od2xTzYAk8/zHMaI/SjHapPO7Su6f9JCcJF1wVKVQHIVtWueEYOD7yvaj+BK8f3mJPDKyRxlziGGTioBwmXyvDE4JoqPg2KT57d4zY
  template:
    metadata:
      name: happy-secret
      namespace: happy
    type: Opaque
