apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: no-drbd-loader
  namespace: piraeus-datastore
spec:
  podTemplate:
    spec:
      initContainers:
        - name: drbd-module-loader
          $patch: delete
