---
# Source: authentik/charts/serviceAccount/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "authentik-default"
  labels:
    helm.sh/chart: "serviceAccount-2.1.0"
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "authentik"
    app.kubernetes.io/version: "2.1.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "authentik-default"
subjects:
  - kind: ServiceAccount
    name: authentik
    namespace: "default"
