---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: default
spec:
  encryptedData:
    alertmanager.yaml: AgB/oILqTEI/62XyuVhnqHudnfYDPxYW3avfj75lMEqz76lXLdPd9R0NUw5L5dhAu/eKUi5qjvjPF+X8mRYcoBCr6ovKtpGj4JCVzezaBfWULc2mjHJF1DqYBe9D5Rx9fikEOUhwl8qJcQG9iWKJzTtlARKwF/tBDaFtzYLzeOXR1o+/jxCc4w7Kcv/REncKnN+4oiCZcd2dYKglB433gq4jmbiIWwMQwhPdV1WUQ3CBaL9nvU57OYcAcJl+PabOTRlUpFV3RWMod58Uke7fOR8QNvQ/WSY72LoflP7dOYhfJJkIY7NQ6yYPiJEbbO2lmhwCHnE6BndZPPX3nHVqs1fULXr2oQFmz/ZATj/7hqG04Y9tHhq8Mia7UhmF8GFzFykJdEMba5Nwi09c+0z/9+Eu/Lfagr8zgZbryxhnYhtY+V0X/uSV/ZIFBVULXOQTJCRsmWLO528OvReOvyevNshEPi9I2c9mnKIK9Ocb5PsdC8Zm+Mzm7/RFGJ1IyDCQniaE34pfxcN9GPAu5dABtiI9XqggJsT9v6weR/8i/TPib6aaqxhIWEOZ+3ULBUrHoDQBGhV4pq63oqOwt4B/68moV6XL8N2PLR08n8Ck0q600YANMQ/YmtqHk63j8lSWlWUGneehhqXXEOXCzKdriP1zvTIwApZv4i+AZAcVPJdfPbkQxW61JUXkmuYg4S5bi4Ehh0Caxbmi3FS8HXJQPdczEBErnuy2K5XxYjDg4MlynVcurpq15S1+dO4PA5YmSUFYLnkUOjld5seulw+yAQjZSZByqnmyhs9Fw2ka+2umsZhBE6MEKHCbM1yXHhss+pT6DPopMTkT5AR594l2aN/GXSCg+NwL84zFRr3a6+txSnQEfondYp/j5rjqTf6b5e/NuVV7MW86vOR8Vt9EGAS/V1oCFMgtDl2fQN6FUSz3fR09CVXBJbEGppqfsxObO1CkYUkPq2VdyJJ7f5PNRJm/9ewKWjoti/WScRaniBSiMMuoq8sEUSj02TTqyV2gMZysibLwFmT9L/YkZWoSpMvfrxmRqbx5sl+wYi44L0MyNEYaIm/TQe5eGvnhAysP5MyKpFXfCWt3QNe/fuj0IECJAatp/aFoaqfSDOGvLaLhdzYNnjXrXkom3lxBh+goY0Qe74DL9l3hseHQn818JXmmI9+HRo6GKKcIZPm9k5/4LOHfJ2/+t6ydf60ezDsTccy8capDzKV1k+G6C9QQ2Nllgzl7hHl9rTjy6kja6nFSaXXsT7qAtsZBafPHStCR9YoYeQ2LEBtTwSV9ThBSvWLcvrSsxGbnldSh7xLNzBpTmpsPOWP2d997v/T53dDeeNmqS79Y5HRulwNNNCqHKnQ+T+Gj5ch1NSsy9OnRBaqQDNGrCkoqblpPaekKvgSEU6mIufjDzHETnkm/i8cvHLhtSbICEGnAuDQ4rZ3IAwS9hp+SwhAhKts7ZmzW02qJO9LBJnAhxjX4rPmQtezjN2TV6lL72aUBwhCO1LYimjDY8EBGemYkdGQQBtKoQKtAAl2rZXntBA+5L59jQa/4Ot8yVyejPgQ43bicIDnK74tI2RHql1kRsH+82zKcRr9qEYQJ2RHVCaLkTX2leVrHFav7+nL12js7l5b8FTXAIg/GKffAKpYO
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 75.9.0
        chart: kube-prometheus-stack-75.9.0
        heritage: Helm
        release: monitoring
      name: alertmanager-monitoring-kube-prometheus-alertmanager
      namespace: default
