---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-acme-cfapi-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBgeR2zx/7xDFjX+tuLRtDw0iq0ufuK3kQ8/lWotAJ2ed29H9mDeK1T5hBIXXmS04ejVpYCu+ki+Cl8H9tGttZtM290O/QsHvPV5YHegdL4g2fGViCzrSkktvn3hy2hJmZVUrZZUi2bXhC6FyVZMKb6oO5u20BTGKvAo4N0+Z08FpED9n/ZEM99Z7Y9G9zpirlkA4vRwJgpQEFltMUj1r/bnYnT9SMTp5jpZwA574YJMohngluq+1zDbbaGV1UNIx/U/n/Z2zo0WIx7Fp7TNxi2Qe7oyrkkfqnt7d6TkcS6bsBtMz/YuH11zGY40bqcO9YUKpArxtWaSzHF3lUGMmpEQ+GWaV8JfR2bKF9vDgHTo6ruBiuIAy8E9MWhiJTEwCUkOgmR8KecmBRUrk4QLLxHRxuRREeUGSGVbp18pmrWTyXuCGeBPdzHQdL/PZ7bcz1VbE0Ib+pLHQzsFfd8PDG8smDG5SQOcyPLqPgIXYKGil2jUl32O8q5j0updEWKHUeHLAxrATXB3mMWifAcMnPiaSyDxkWuSHzz6xkzYzPMVzvF2OYQ1vqTSSLxvld012OHjXZm6wT4Es7lBcyZaZ6YgVBBP9V1I0VQQicx/ABJDDVgNVkCQmHDcE6Sdl0KmdvWefEWrX2DZ3yKjGJbZfbR3vO3JAgXYJn4sKiOofQQlG7LYAdTxoWG9xXZ69aE0EzHDvrGBUR5FUWqLyhJDnb+GdOuPwvTHX6oI90CZcihDEAoH72z/cmH
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-acme-cfapi-token
      namespace: cert-manager
