---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: objectstorage-minio
  namespace: default
spec:
  encryptedData:
    root-password: AgC4y1XBTD+qMqO4NaCXdRMNB5b5Ha+hRCPtpkWwOmcH3GpZjH/iR40j3XBK/AKqUnN55GPS+66U4QV9aIMJilKs8KjLot70htnXJIjU2ma0wycvXWCw1h04aJcc2u+GoeDg0+Jbu6tDVYteCQCs0+xM23/XpZGc+YZIcGg6pA4AcKEO68N0Fg7pNEqeTr9hb28t8znyLvKZRSwfOqlHbuUZh5UKv/JBZ+xP3Rv9KGFtc/CPosxlLjigmru4XlIHuDWcW4Fr7psBrXH+7kv0RPRB5D2eoTWadk+fPp8ZW945zE67/KGlXgTFfi7t2kojMvXpJS+lXXMfKM9vTejPMW+6YHwritcx6c1P3eJPi2ex3EJpQx94DY7fhzymIZDGogmxJkkAqkrfrxjTO4MdiKFmbl+Hx/HtJnkGkdmxbKuxyIdD/vhaxBr9EWFSm5Qj2fWZDFpJhBIsWPgQwA4IlivjYg280CrOGt5DEyJYZ61mwQxbmnLRCnpwURsdgPblahN7a06AGrdsSxBLlkLgmvkjo0j2kWz9PUHDVn3xZJGzi45CfAfc3T5lKTf+dpO/oBPkmPk/cSca6Rdy+dLxzsoFYhF7qBQE61nHP/e6Qiv8kCRV6j2oVzLILuFg7k8hqnUD4MmWEFQug0z9z960vFoGG1Wb1gKfn0Fh9EXTkv3cyfuk7ok8ResDfDTxJrPioNBDt9zz0Un3VOzdSUYKVHWmhzKEjE5LQ/QJ42aipymVFA==
    root-user: AgCTl95v7wzY6tIdzjKgxJHfZ8HIM8c3t2WQIYVd5ni0RyyG0VICtmMbAOGMjAXUBS3YTMMKRIKbfedPK5xwJMkO8PWekcPb5ZgujJrDFByBIeCBrnnbrK/LsmF52lmdqXJp96SfktBVQ2k2Q4+UQEUsAwF4gs4RHuu5Ue2r/Po+Bkmb2hB+cYksFF9crLQ8wHw3aX463VKy64dMH1tqvC2QqL/hTyH3rjjtijBLkR9A+mOgkLAQuNqwQGO1DhPf7eCad2QriaMvUGvqocaOxIoIAsHZQ0iq0gHEnMJ0iF+iFTZMSmR+SPZy/Xfg8qCUYgrQQUIobxHd2tAwrWKWUOF3SCHjAVh0fVEbUyn4J+xYrLvyA3p6IWvdtN03aBhNfapW5xP2I1fmAKMqI1HDo7vhYgOezZ6fiI1VTYx4q3cMYe/OVZbdBbz6hD03p9siDXkdy+nGv2nJuE+lc5TvFrJcF3FdxWWNK1PzCm/La27KWF+DPzJ/iGPaPzk1+LStrXuHx0y/JecRtV9VVlTW+2L7yYYenrimW8qFoDWPWurDb/28V9nlODne93brPQxrukGAgjZcacNIhm5eOgQ6/p6UnwE8AdKAOn2+GngdudaLUk/94Oj9fIeKa6uAAUfT1YzuvWNIlxxQtI2eOh5a1oQKuI/3+mQA27c7qBm7zZB1R/LpE5+Sk4XGeSMaiPZyUOJi+nXV2wo=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: minio
        app.kubernetes.io/instance: objectstorage
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: minio
        app.kubernetes.io/part-of: minio
        app.kubernetes.io/version: 2025.6.13
        helm.sh/chart: minio-17.0.11
      name: objectstorage-minio
      namespace: default
    type: Opaque
