apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: minio-transport
  namespace: default
spec:
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 600s
    idleConnTimeout: 600s

