---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgresql
  namespace: default
spec:
  encryptedData:
    password: AgAMBd5IBDb/HO+vGI9hZ0e1muXpYXB9qVITDc0Ty7Dj5grPrIH4hbrEZ+khbSu8ueRSl9PQDd9J9GtfoKKV4c1bNk04p5SFc1afVhMtlV3Ypyh65LjWMJIAksoyqqFuWoeB4rqVSsJe/gP1ZL8xdzOV2AUTsHM9qRrLCW1pL+ZH28RNyD+mKATu5QX5ua+Zc+h8DhFsBIE7lmaIP98xjrlyjuLVtOYVkEID29in4QTzKTlp9Svz9JmyFnQLduYifUKM2Rr8ZXgA1Pvcz3Qf5AkYroKhA8dqL8mRaUrYR6bvcgst/RruyZx8A4xEXvDrhmLnUBk4wUeNvpYrsZzmsUYNU/YA27QeOux+cD28Qg1S4f3QUwFBXktEkP01O0iJx3BPgTQTq7NwKI21pXRkT6nlW2VMHF6hlXuB3m1Erdly5h5Gn6o6/pjkUfjJjVL02bwdvcwg1UOq24ZCV9ds4MQ3x/xZkI2N/6GBBPBkrfrQQ2dVB0BkrqeFCyLyrxJy1c3x+9r7oSZc6OHWvDMKF474y6eweyhvbJ5je/lnj8EBrqky4iICXnnTtXPbvdKFvFzdaqdEaK53NfOxCPhj+0fN3/q4Gg9R9012AtUuy9fFrpSJY3B05jQF8kROZ6BwdapZTBS+icQabC9yv7tVN416x9VrT1EPttMDFCUoX8ZHEqY7vfUnPZEOWb5DwNV/mAHaN7StcWXuHfg0T89TbsvPqK15t0tV5HOsSskCd2BvOMKCsSlixt5hhRQ5zXwPlLgDA3vGWkD4Xe9ouYLQ831z
    postgres-password: AgA+HPhF+vl+TBRqlHOIZasyF2i14LbCdHKyuzRmOcasj/raoUZqUEkGekao1glfgTgPOHT+PIYyH142UmgCNkK3mvflAGXk/bzMcAVtuYtv/SUK34SkPLTI7I2w9VBQbyNaYp3FawiLlCnrbMNWB41a2EQ829aedmmmyON+SoH4sw2y+2XK431pxO3NndpR5ZN6jNzEHC7Q5wAtiPLzixwm4ASyE6d7mlPztj8jHp19xqpn1mp2iJc2jL+GZvLWZe8rnXPN65Ywd+mWecnuurdxLe56AxB4N7bSzCrOc/+bkblzh6+jeCQqqUpIHmRDHlYDr23Xq36uJV+T4fywhZak9LEaErNUs20C1Mww7AlI+5AGv+FA2OcEozToQQwfyln0rJslyR2x3Kb3109fahATlBB3Xu0fAde1HsleRBgx/6seQ7RgyC4nwoCqDYXietTpPlBB595CZ2JrV3I5LqibOv9x3bRccB1mHZyr5Zsr8RygvDEAOriHp2C5n9wdR5rDopX0PgUTcaUPUWhbtujBab+cKxRoNt3Gb2ElgtgwoK6RDjxvqaQEshkF4aum4/cgfTr7aL58zBH/MW2TXpGa8w94fE/52wjWnG6kYy6KVNJvSs5G0FJXvhnTThwjINkFjXV3s93TUvKPIVReM8rv5goPpXkYzwWVStniKWZntdNk9MXoaSzmBRcHaW8ORjY9Xh+3pGmTRODO
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: authentik
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 17.5.0
        helm.sh/chart: postgresql-16.7.4
      name: authentik-postgresql
      namespace: default
    type: Opaque
