apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: paseo
spec:
  encryptedData:
    .dockerconfigjson: AgDD4rnHpRqb29nZA910oYn468YzAY4JXMmow4VWgkLVT5pU8yw4zWCvAkVGUTh207WYcHkxM1bkqpBh8075OAAz2mqN69t+TAEiEbtdeWvvVUgfu0LhJPc6oUOY9djLFRjvvjIge+EIioHW7m/Q2HUoTM/JPEkqib3U209fAn5Yjwayddj0OUMJRIctg9d9nTBO2uSjlvzJ8SwgTwJw45Tn13oRH5JhSl7dY1j6YwxzHJZTkLpytdZJJ+XxQgc8CwoZGMJnEm4FUh476DpzACEDL2pQkKLPdNZXkDKZ/kPQ2L6EWITuvOfyZnrMWecgmksCUWhOrkAqk3vGs9cf6rz3JdT3VQY+2UBuwty+dgEWYGDIri02PqrSMsTJtn3uk2rPmregrEGyp9R1wGedCgbjPVzjTXA5Dar4huIO4aUZJ6kG4jJVImXv4O6ToEh0R7XZOsP9Jz0pDn4ERaUQ+DFjp/+TZO7iJGcmQ/bU09G2IORgbQDa+bfM0gChmFEVJupR4jHXNYvaxaWj4XPNtChKlKnVjOHcHwR9p0WAkQ6NuvRVJvOCzDHkiRMuCi2mx87yyiYo51GI0kPC07okhs1gQe+9BcijykwyrcbcbgH34BzeEV5dx9OpbMP4ktvqkuPnXj9MEnwzB0tZK5BgYwCr2Qq7yale0PKjVhND9/XKqWYzvY/nx/kEu8BUQh0SiPw9oi9fv7xptWSyHULCIa+Zk5UMn13IH0+ZfesKXAt1ckcM4BjXkwgMNIgo0TEWZUZ+Ga8F+fFYnW9j3y/4QN/I40Ag16biWQSFbThY69Vl+SzRBqQ2J3Ce6rM9WWZLh4AbKv52PLs9R1qff/VbJ5GYiIRP6D3/KsEKjKNOPbZkaVwSjf/x2868FzlEw9Fg+jE0fVhQSuLupduB6O9Z90BKqrQqgUTJz6sw44U=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: paseo
    type: kubernetes.io/dockerconfigjson
