apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: paseo
  annotations:
    external-dns.alpha.kubernetes.io/target: 202.215.58.76
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paseo.mtaku3.com`)
      kind: Rule
      middlewares:
        - name: tinyauth
          namespace: traefik
      services:
        - name: paseo-web
          port: http
  tls:
    secretName: web-tls-cert
