apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard

spec:
  secretName: traefik-dashboard-tls
  dnsNames:
    - traefik.mtaku3.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
