apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgresql/primary/extended-configmap.yaml
- postgresql/primary/networkpolicy.yaml
- postgresql/primary/pdb.yaml
- postgresql/primary/statefulset.yaml
- postgresql/primary/svc-headless.yaml
- postgresql/primary/svc.yaml
- postgresql/secrets.yaml
- postgresql/serviceaccount.yaml
- redis/configmap.yaml
- redis/headless-svc.yaml
- redis/health-configmap.yaml
- redis/master/application.yaml
- redis/master/pdb.yaml
- redis/master/service.yaml
- redis/master/serviceaccount.yaml
- redis/networkpolicy.yaml
- redis/scripts-configmap.yaml
- secret.yaml
- server/deployment.yaml
- server/service.yaml
- server/certificate.yaml
- server/ingressroute.yaml
- serviceAccount/clusterrole.yaml
- serviceAccount/clusterrolebinding.yaml
- serviceAccount/role.yaml
- serviceAccount/rolebinding.yaml
- serviceAccount/serviceaccount.yaml
- worker/deployment.yaml
