helmCharts:
  - repo: http://charts.gitlab.io/
    name: gitlab
    version: "9.5.0"
    namespace: gitlab
    releaseName: gitlab
    valuesFile: values.yaml

resources:
  - web/certificate.yaml
  - web/ingress-route.yaml
  - registry/certificate.yaml
  - registry/ingress-route.yaml
