helmCharts:
  - repo: http://charts.gitlab.io/
    name: gitlab
    version: "9.11.6"
    namespace: gitlab
    releaseName: gitlab
    valuesFile: values.yaml

resources:
  - certificate.yaml
  - ingress-route.yaml
