global:
  hosts:
    domain: mtaku3.com

  ingress:
    enabled: false
    configureCertmanager: false

  hpa:
    apiVersion: autoscaling/v2

  pdb:
    apiVersion: policy/v1

  minio:
    replicas: 1
gitlab-runner:
  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
          image = "ubuntu:22.04"
          privileged = true
        [[runners.kubernetes.volumes.empty_dir]]
          name = "docker-certs"
          mount_path = "/certs/client"
          medium = "Memory"
        {{- if .Values.global.minio.enabled }}
        [runners.cache]
          Type = "s3"
          Path = "gitlab-runner"
          Shared = true
          [runners.cache.s3]
            ServerAddress = {{ include "gitlab-runner.cache-tpl.s3ServerAddress" . }}
            BucketName = "runner-cache"
            BucketLocation = "us-east-1"
            Insecure = false
        {{ end }}

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    workerProcesses: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    concurrency: 5
    resources:
      requests:
        cpu: 100m
        memory: 1G
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  kas:
    enabled: false
  registry:
    minReplicas: 1
    maxReplicas: 1
  gitlab-exporter:
    enabled: false
  mailroom:
    enabled: false

prometheus:
  install: false

nginx-ingress:
  enabled: false

installCertmanager: false
