apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mt4jm-helm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - plugin:
        configMapRef:
          name: github-sha-plugin
        input:
          parameters:
            owner: mtaku3
            repo: miubiq-t4-job-manager
            branch: main
            appSecretName: repo-mt4jm
        requeueAfterSeconds: 300
  template:
    metadata:
      name: mt4jm-helm
    spec:
      project: default
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: mt4jm-secret
          namespace: mt4jm
          jsonPointers:
            - /data
            - /stringData
      sources:
        - repoURL: https://github.com/mtaku3/miubiq-t4-job-manager.git
          targetRevision: "{{.sha}}"
          path: charts/miubiq-t4-job-manager
          helm:
            releaseName: mt4jm
            valueFiles:
              - $values/dev/mt4jm/values.yaml
            valuesObject:
              web:
                image:
                  tag: "sha-{{.short_sha_7}}"
                  pullPolicy: IfNotPresent
              t4Controller:
                image:
                  tag: "sha-{{.short_sha_7}}"
                  pullPolicy: IfNotPresent
              dbMigrate:
                image:
                  tag: "sha-{{.short_sha_7}}"
                  pullPolicy: IfNotPresent
        - repoURL: https://github.com/mtaku3/homelab-manifest.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: mt4jm
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
