---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: mt4jm
spec:
  encryptedData:
    .dockerconfigjson: AgCOxxxRkDVF57duLugHJ6nE7T6x9tFZntUb+Reidbz0t565oIuglc3bixLztlsMwi4g/kiwpCgvT5yr1bhmfbh9rMeunttyqfcQIPSD7tIQidVBmeaGd2/9bqgpmeMrE/iI86RxWWYD9BmUGOJ4RkCy/VIHlcC+9fzc+TDFls06HMxC/c8M/jcCWq9A3XjnSNJk2YoYOyvoCy4XLz12YVeVjI87nOhMLqvE1jInAfKoFXww0vaOBSxOUJ+D95kV5d8NxIEmNG+XIYuR8XLjXRv2S9dD1Ncy7QZysUEPR+6iUTv2ep3KQ3T4TLUfzTOdSH3cCYXxxf2sCVbwBSQWd92HyWVoKtuEboGUenB6Z+DK61fRTKuM7odoKr2iSMAYF2B15RZszxKLbZo24PT0U0iw0usYxDg3MH3kgjKyb39Pxh+p96iT1Zbs/qMMwv3bXwww972rIV9HYaSsJmLZY4U3VQ0igUoWKDGN0QnwyQrAWTONidLjKPHS5/37nLctCrgPXqhc5Ltvn+ybWE/YH+qAg8GLCFproqRh6TbAqRBVustp8Cu3BQ6bSAK5GhwNmar/gRl4dDJ54cRArOlEFZCrLKZX5Xx1mrpZpOo38LV6ibefo1rSeyix5YyRZVRvNpgGwsuPzp6GC8cD0kvt0VWatImsVi4FOzi2YQP3LIHwJvCKSGIfPhG6ZwAgCn5eDyHNaM4MWhqVGaI/O9KBPrQqeBBafCeZYAGb7I44SBDAS3nmDum44uNh/Yvzju5Ylaal41EJG0Ff39QOcmYJr4nKTsM/ZVekSUL2pvXbtdtWcTgRPH0O8cxd8sj2BchfMSYWIGdvfkyuhcssxO/A3QxK/QhI6VW2UVuqp8vBMG89JTKrHnTPl0YaIvKQtjkSUjDrh2XgUZrZnTQPFY0M6MomorwqhcfrIXpo1rY=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: mt4jm
    type: kubernetes.io/dockerconfigjson
