---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mt4jm-postgres-auth
  namespace: mt4jm
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBuD0sBTNPhJiQoZsdnXBgdM0ZQqQ+d7FqsJEoAViIwI57+1e1qkbpuMIoFSW3tM+m1rxGKGsFZEKgspB4QZIEwY96zbrgPW+PlexP9XWDvU34fitHTofc5t4sfDS3uh0IoXhW75YfULhu5E54StByfXoyS0IE/spLaHnWqiBYSWfx+6FgSAtxBhGXxPXfOVUKIjx+m/xArxeTCDiwBuGbRssa+v9FwnA+qL8tLyGcXQ9N0qU5FFDMp9ZGs3xdRjsca6qowdANgelsne1myrQ8HRw/oLaXZz7yGlklxp7lh5Klza1PINpRAOnS8Krg9Wp1D6xdaAZiBgEARa6Xt2SdVml3MKD7ilq1ChnopTMddP7xgtheklbDHh4JF4t4MoWfZymbMzOoZU4UHZ5pG+RrHQtclNBp7LftwHDRQyp6XNsL7GcSe8XtQft5EyzH8qJ2xV9f0s9SVL73TeXRS3Fl8gPuzpxds1E7pLJABGQ8+2viGDVfMSNRTmGI7r9TLPHU8gkQLR+qVKhP+YH54SMIrwwX4cSuVT6NtpyPtBAyLZHTStonN2XCERhcJ7vcnBpooHzLq6DSD6uEuDK02neg97FTjgYxoPCtIO80YE70cySPReSctvh7s+sjehqJjHyk+jKHiFU6p+pmzTr8PlnF4PbKRmA/TxICZZJBT4nowRjQWfNxIS104I6a+jBOjBRRCunjz0BdKCKJ0UDQSfzheTS9xit/6RHjvblsjQnQX/A==
  template:
    metadata:
      name: mt4jm-postgres-auth
      namespace: mt4jm
