---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mt4jm-secret
  namespace: mt4jm
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBjvZ01qoFFssIVNR9Vgz/VH2vCBVjKba7mV830R5KPnjy1oYSC7w4i60MvQyCKqxIO7kUIutOZ8Qr0voALW+X7eKda3LCEGwTb3eS6pnD7HfYlSSOtaqh0hyA6IuKf6I6I47DlfTKZFkeDhe3Flcckh2F7FqJnMOe5n5W76tEpRHM9lQcI46Z6gZrLEK7LkO0t9X1HUTKBVbXfU1hb2JsDA1NZIm3t0hOXIpknWYYgwpmiPylRYLUb5qgRegc+UVGTIXpKMJUw26RuMlw647ixEFgD+9nygKRTTcmh3+dvRgY3hXK+wAnd/NBDJd/mAo7LXdaBPK4PAWAibtLL+LqSJelH4at4HIPkp9BidMosBTCDTft0isP/efOr+9ZzdN8n/rzDd49lFRx2py5nynNfPuhnMN9uIHM5N2gnviphsu2ccPqdKujuvLZ4e121HI37KKWPZHkB0sXKMusZjHpKj+MgtDaOMa8Y97Wj5hO8oN/AnI6/QYLtDBT328923UQk2kmINs8y+VAHL0idYgc3EmPhkK9eqL1avZne8Rp7EQTE4QRH7c/wWwHxidv1A8/YfacZkMfstczFAGVMFLC5NLKkbuB4KwOlehZmAKbMFW1ihy68Bsux4zeBuYAnsfxvw6CCk4uVMG3Gs1Iez32TApNPk9zXTM9FCJQhbuZW4BfDOnS/WKe6YdcEid8daRyPDxJ1tKbNV8sZilfc1C8lvEqLd2XcebrFkO4jX1EzZZlm/76duSwiZnSBMA==
  template:
    metadata:
      name: mt4jm-secret
      namespace: mt4jm
