apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mt4jm-pr
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: mtaku3
          repo: miubiq-t4-job-manager
        requeueAfterSeconds: 300
  template:
    metadata:
      name: "mt4jm-pr-{{.number}}"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/mtaku3/miubiq-t4-job-manager.git
          targetRevision: "{{.head_sha}}"
          path: charts/miubiq-t4-job-manager
          helm:
            releaseName: "mt4jm-pr-{{.number}}"
            values: |
              namespace: mt4jm-pr-{{.number}}
              fullnameOverride: mt4jm-pr-{{.number}}
              web:
                image:
                  repository: ghcr.io/mtaku3/miubiq-t4-job-manager-web
                  tag: "sha-{{.head_short_sha}}"
                  pullPolicy: IfNotPresent
                ingress:
                  enabled: false
              t4Controller:
                image:
                  repository: ghcr.io/mtaku3/miubiq-t4-job-manager-t4-controller
                  tag: "sha-{{.head_short_sha}}"
                  pullPolicy: IfNotPresent
              dbMigrate:
                image:
                  repository: ghcr.io/mtaku3/miubiq-t4-job-manager-t4-controller
                  tag: "sha-{{.head_short_sha}}"
                  pullPolicy: IfNotPresent
              postgresql:
                auth:
                  database: t4_job_manager
      destination:
        server: https://kubernetes.default.svc
        namespace: "mt4jm-pr-{{.number}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: ""
          kind: Secret
          jsonPointers:
            - /data
            - /stringData
