---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-apikey-secret
  namespace: cert-manager
spec:
  encryptedData:
    apikey: AgDA37QuKJ3NgVjvBaLChqDp1TBYvsvkHVihIeCZ2i4dVlM3pd06qztZC5VEro6SjxngFZfIbOl8/iFzJX4AW3it/Ak3jYTSkwf7LVcrZQGVIgajLDQxJpayrAf9luhDZexvazAZ96PJ41r0EK+2xvJKthtEsuUC1HkZjQ7SuHQWWx6roZioH4tSCJjs93iWiAwSO8uTduzvXtsHvWUYfqyN7BbNI5m6ARamcrygHAB8r3k5rFve4THt1Nh2z5CZZhojNyPVv/MnvpPHpTEx1XRlvZbA+V/UXfKRW4bPQZpyKQeq2zimhmRLGktsMrT1HXLeLv8Ih0Wqxr/glt56K9Vg6RMBpqw5pKw+cTSlyjdr/shC6z1q2Gs4kQjDpIb5pbVFEmO4tJBkjjgOD17r4wFRXVrFepo3uKuccEg3uRaIcDhroJCCPlt5xs6Rx7SixVzo+73HZJUwKIpv6Wn/XOhfftFYbFs//pAxAJLbudioaMvh54zVScTgb3vK0OlqpF4CllL7H+GgyOyT1iL7KiZ59ZilHhHPrD2Z5m+XXHFWyTKgIVNTgPSc1UHuOHxvBQsK6LPR8cevEsCB/Cxcv74TkthuKpXrUtFabAeJw1vnLwATN8Fr7BO1V1FTpoEXzW7rtIUOhG567a/1JX0jN3dGgwtoVZ/rapB2xJI0VaQdeCofFjrkHNTGlYEKocsXw0ZL0hXwjdMvEJYFicl90Lfh8U4GvBJ6OmgoCkC7PAKlGN+LZG452BER
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-apikey-secret
      namespace: cert-manager
    type: Opaque
