---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-apikey-secret
  namespace: cert-manager
spec:
  encryptedData:
    apikey: AgA7EMuDq63pnMZ+7zSr89A2GzcrSxNRGD17u6g/x1Ho5dW0Y4/0OkTHmmgDTFt8vi2qJMAbOPZMeKUn9O0o9xztqiQSEaqdknPfIbVymFikxwTl96wnDDxVOVjryspC3BWG840nAVnJkijM7Ke8jJJtdebrTyQc5jGQzeETWdFMv/HPTTLKoUFwY1R9FNff7vzGGoAhuTnXFZWzZNKrfLD4GQqOxUnBY71gCpVxR2KfhpXyQrXH7P1ZKOFMIPTdNrylOijybxclbeYq+gdLkJxQ01pAIQgnkvMGzwHgIN+q84On86V0dMZ3vdQW8qL5lHiPQBnRMMav4+6hI5tyb2SXp31qpnoU/m3r4kzuShdPKqJJZSsMS6LBfPz30YySLNQmXR7Velitz86dUxhsuULeGo5sYndVfxDjkASsZd/hp7hgIYTYJjhS7La79oWz5AMNvCt24+aKFFEKbc45gLgsa+w8lI7ddYZ5i6RfhG8YfEjoRyfU28ZPohhenH9AY/StJhgXNw4cppq+LDPy38kR3KIfhX9ZJMy6jzl78GWA2js+ITNRy8UkVLoeuRBNK4GzSEr/nCXbzRUZX5ZR5U16cIdlBvG9FGS3RTaxTpj6M0RQWdOWTDWVE7JHX8ucQPeCM7ulMFGgML3iHjRMBl0R3NJmK8KAEGM6YnwbGEfaFIeYJ73ypc5QgAsV2ldplbMiLevJuOQmSOYQ1CPiIoWeSbaGu0uZ1Ain+3C/FH3LnadK6YQGF76W
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-apikey-secret
      namespace: cert-manager
    type: Opaque
