helmCharts:
  - repo: https://traefik.github.io/charts
    name: traefik
    version: "37.4.0"
    includeCRDs: true
    namespace: traefik
    releaseName: traefik
    valuesFile: values.yaml

resources:
  - tinyauth/certificate.yaml
  - tinyauth/deployment.yaml
  - tinyauth/google-sso-secret.yaml
  - tinyauth/ingress-route.yaml
  - tinyauth/service.yaml
  - tinyauth/middleware.yaml
