providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true

logs:
  general:
    format: json

service:
  type: NodePort
  externalIPs:
    - 192.168.10.2
    - 202.215.58.76
