ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true

logs:
  general:
    format: json
    level: WARN

service:
  type: NodePort

ports:
  web:
    nodePort: 80
  websecure:
    nodePort: 443
