apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
  namespace: cli-proxy-api
spec:
  secretName: web-tls-cert
  dnsNames:
    - cliproxy.mtaku3.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
