---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cli-proxy-api-management
  namespace: cli-proxy-api
spec:
  encryptedData:
    MANAGEMENT_PASSWORD: AgDKX0hzRt9OV+HEwYcT3rR1R6ZdKkGOjYKBDEOKOO1icLN5nOK4ax62H3bvFE9pgViWYuVQfP8BHqPDDRtpOOh3II/NZS3iV9zoq+1RrqwzxPwI/jZIyEMO1bWevfg9a2SWi178AoaAVPZuAMec1a4KCVyu5UcF/pXny9Jmy4WDSdTXzksn8MJ83WszFqzoLzUylxkzXTKi0dr0zgCHbntWWqoP+8MCK9B74Nkap0ANzxDn6JQ3pTzLQYB3d/mjt+oCYZVJSyVvlo4+OSredgCOYzs/U8R4uczZvknL/zdlaKUMx7W6gD8OJ8u5LIn6eWmf6uduYlF5oyeXg4w14y1s1kuL7VJ/Tt9pSWPlQMWnPe1fFf+YBbRTO6XVmmhiwGbw9/kB2Rf3Bn/PbROSHImsNn/O9PowJX+vOsIK64MfW2YEar9NJIhFJSwHdNOhA2KVMU+X5jXDq751EPISGUs4LxJlNyShjlMyB7ZqRuQjVtCwi8rs3Q+YRQPc5m10iMU25Qgj4bodQQI0Kc8gOzknGGeFeAX87uvXWagxZg3wm0wrfhak2xkNjhhCgOINQYDCZ+Kc9pXqp6sMqBvG4pPDky1kz047oQ9yvqjWhETker+p3/DG3QfONLtKhBi7wd+36HVDrR25gMOWQ+EpNFgwZZ+NCfz1smK02KZ4CQMJft2rvm50jPtI19KH2dn4BDoFJAImDK573F3vQT0FytITSTyPQB13fsop1nqptDUxOiLqbyskzKqn
  template:
    metadata:
      name: cli-proxy-api-management
      namespace: cli-proxy-api
    type: Opaque
