---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-sso-secret
  namespace: victoria-metrics
spec:
  encryptedData:
    client-id: AgACNLnyM2rwx5Q/ygAydz5RTaFJXBYStJSOuQtslZzxp3tLyBT65/S9aawQzAwHwkgTIYZsgAX6z3iOLXkt9bktf5MNPtwzalzZztgCxc9fxiooFLfIq02ftp3O7cL6WOW8eDGw8GPN2JieC7RK84hYbAI1QyEpIXXB2lQId1bazhCNNCIsVOatdTuZSlLYCTy6nkyjWAb9rCy598kyFdfjokWuCDiMiqu/ZjzmUgg+jl6ye3U4nMGKzL2bztiT98+AkvVAhNJ0yFT/a8rIIcmlbNdUbpAWxzNVvrWpb7vd9336eWrCenZNQ2qMczTgEXyLDMihX83cTCcWrWS3hhtPuEGWZWHM3UwUx8AcK7NfhRVZWciIcyJIlQvj1DheX808cagq/cJDdDJfI6ptoV5U8AgXfRK8ZIqclQA/Y1f+t+QDCJo6X5XaNDT0JJjdaUhAaV9BYBWMKh5ZKL3dl4CTDdTOmjGB8iJX4h+3nzpO8hIqnk56Hxzy02PDX9NpI3PN2EEh4fN6nctyx6GvJF6VyxJ5EUMXQFU/EnPtUENEoGdFzs8HIanL4U9Guytkzfih6g/AaiEyqatpiijC0qVR5c3oEh1rngIW3B9h/7RLCIbw+VYXEaT4r8ALHYwH7Y82UnrTE7GHuRX8QazVxkWYCkgxJ+l+ZcpD+c8Cp7bTfZCV9IG75ohkxfOSayziJAeV4TU4+fE0LRXyrM4TxsKTnQdcEdsh2ibbA1xKdyrYtV5SSFZ7JoH+FOkoX7UxRcko2yWTIJ1Hb/AOOjtkXUfHbyixjydKOg8=
    client-secret: AgADfqWaDPkyMsaQXjyNaSUyA7am/toNxlmzRhEp8gsfxyv0NwgY+5PMX++6CfmZ+QdxUvHesyPKl5jOQ4ueff41zw1TfjKFw1l/kD18D/M01H0QygLX36A3lUTNXECqIvYXgT0SjHUJJwp95OGTP9sulnANdaTCApNq6d9dlqDto1oBzy26SQb+2pwhgIjIyWTEsrU+r5F82w3+XfBmrZMG5RAH+jEqB+UAGDEzIpmU43QUQQcGgBpjcU2MkFv6+nuwyhXML8TRe5l9nzqy/9YwYJlaUtWB+Q9nume62wkwhW25zAtVV5hAe9hq4Hk772gyq2HHc9KLkXor6UcDDectOmOBEBtp3Qv4P0WJp0B5IFTqBpwDMOWfmHAeaNxpqCJWvORS8Np3DpZExdMr5nbt1Ejo2yOgVFYOqULwdcCD3Oi67JZ4YrhEe6hhf/Sb2RpKojwl4XYfq5UfyfLHneRZ04yrQF32rEV/7MwBGmG6SrxUBbyau0zf6jVQzWhKp46I5cp9+6PbkUc8FlJmc1D3aw2nPoYkjEDhEio308Z5+u70wYdxjSz4NcXJ0jqk04Wml/u/vAz4/40C5LDnR6VlyyzPKfdOZq2Iv0xns/Bbs2t75sCL4lew60I7cmYqqfLK1leG7I3a5lhvU3YXJsUbkGe528+HKYXQweHy01jxv0B+D4HXqOc/PGfsyZeGW7cH0lZdWdDzGsnPKE6cJSMkM0jY5qIdRzLxHnHCL3S2V2rt3w==
  template:
    metadata:
      creationTimestamp: null
      name: google-sso-secret
      namespace: victoria-metrics
