helmCharts:
  - repo: https://charts.obot.ai
    name: obot
    version: "v0.19.0"
    namespace: obot
    releaseName: obot
    valuesFile: values.yaml
  - repo: oci://registry-1.docker.io/cloudpirates
    name: postgres
    version: "0.19.0"
    namespace: obot
    releaseName: obot-postgres
    valuesFile: postgres-values.yaml

resources:
  - certificate.yaml
  - ingress-route.yaml
  - postgres-secret.yaml
  - obot-secret.yaml
