config:
  existingSecret: "obot-secret"
  OBOT_SERVER_ENCRYPTION_PROVIDER: "custom"
  OBOT_SERVER_MCPRUNTIME_BACKEND: "kubernetes"
  OBOT_SERVER_NANOBOT_INTEGRATION: false

extraEnv:
  OBOT_SERVER_ENCRYPTION_CONFIG_FILE: "/config/encryption.yaml"

ingress:
  enabled: false

persistence:
  enabled: true
  size: 8Gi
