config:
  OBOT_SERVER_DSN: "postgres://placeholder"
  OBOT_SERVER_HOSTNAME: "https://obot.mtaku3.com"
  OBOT_SERVER_ENABLE_AUTHENTICATION: true
  OBOT_SERVER_AUTH_OWNER_EMAILS: "me@mtaku3.com"
  OBOT_SERVER_ENCRYPTION_PROVIDER: "custom"
  OBOT_SERVER_MCPRUNTIME_BACKEND: "kubernetes"

extraEnvFrom:
  - secretRef:
      name: obot-secret

ingress:
  enabled: false

persistence:
  enabled: true
  size: 8Gi
