config:
  existingSecret: "obot-secret"
  OBOT_SERVER_ENCRYPTION_PROVIDER: "custom"
  OBOT_SERVER_MCPRUNTIME_BACKEND: "kubernetes"

ingress:
  enabled: false

persistence:
  enabled: true
  size: 8Gi
