---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: mfsm
spec:
  encryptedData:
    .dockerconfigjson: AgAh0nCj3RuqMFHFkB2C7ASs7qLNSyPpXnHg6pmh9iGMx8wgW9ygSM5PcXAGB/y657t2bdMIQGG3OZOk8XxA9DeYkGJac570ffX4kM3CNM6Ev4kte//fr+FVcFTXuS6ZXA9uVzsLjiRphy1w3dAwhaXYnTDSF52TE8zJNsio3C2/YMurSRpPoebyszzH7BOn8XNcKYyr78T0mtNrzLc65j5q7bgPeugwQLjVquNYCXgE87s0Z8UWZX0dixDEr6cMTTXKLzQFLkGvsM9zlpSV92XJ6nh8qT7XKYabpKVdZPtkDfjbL1Qu1+S+rZM4EfNsc9p+Ahaec9v95ArDnuJPib8a6oOOc14EX2kWoClUnASewAZLIoa8rfV6uNISlsukrXehQoqJqFiQU62qUri3lTL6nwBB5LebcYMP52xWQ0P/PiulRk15h4c07F4EovF9JDirb3WGXgSn+ViuwbsuI8ovC0k+WXvW3bXUudDyWgdHUrVXFZNmeOY4vqCYw5OX9lALFHU5FJm4g2W4e+Z1KOcNQvrltjiuRSO3EAflcNZQcxLQ5KcNF4cGGcfCv0Bt1XbP7wSvCGdxveyGnSdIX9S1kid0JqG1ThMc4MPAaODcY7ZkVGdKjJn4UVVq+Dz/ebnZ0Pwmt9w4plZY7HkQxGHWO3NupPoH1+mD6myvSe19bwhVr3ItMcfBB58lVCnsf3ENNkh8fvb1Gzg49RYhSs09BcDk8NhbnlfdlM1/qHgtaafNDtXYM1ROXsbnC5HPALyB50JUothRUI7CRY40XlIBLL7JBfoW83qkB+L3AEap/JfCl7l0ZQzjn89S329EJDtSXFdEEOpspfe6fW2F6C9uoHlLTilO92dFLUfege0WkWC4saPd96lpbHx7wMd+P0qxBgfBFtpY69J95z70BfL6yMOXWR1Dkz3aGbA=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: mfsm
    type: kubernetes.io/dockerconfigjson
