---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fs-monitor-idrac
  namespace: mfsm
spec:
  encryptedData:
    password: AgA7Eb45KllfqLtAmAHnodzQRMX8y/2/MEwccY7m4iR2nQPiRiA5bc8UkN3PIDyu+ixLWDg7FihNaflHxHeLm3W50d1tNtnMV5TyeWh62p7NQISvnKbdmW8BdA+2D8n5Gd6P32B0pKj6plBrSjQou+rtz0nCdb+hiDZejX1AfEaN2JJHQQTAKv+u6GOcr5FUWUOO4Kbz5s0RMMik19qaGRl7rJ7K3CrlMm7nceECmVtcXzVEbt28KZdGJgsBTPEcESjxIsEmpSyHV7ooyDxFSm3tuC3lt8VRI3zpLhaezzmnnjh9VeX9/Rd5rJUYFdxXwsmf9+uFs1D7vpWlZ/lWhUOcXhBF4CQJV5CmEXTmWILnHF0TqxoDdZl697p3eFNZOz0YRCjmquNTL7MXZ7s4pxP4YBgVvrT9mNqzm9ixAXpuWsQxEUiNAxbj9XYdi2klOF5iYd6ID+S4SobKdw5pMbmda4WQ7ZzmUNG4v/6+TVHa8VNYTNlHiOcHN5sxwntDqNXd0rr5V0V6j7INIFZ05ma8gPHwDjp9baOYeeRk3904KPmWyJQdRmdpF2R7hKk4E1S5jhGzFZ5pFbQw1lUuXz8+by9fDYqDbkdsnr3HigHLw0FKT1l2EazW01jX0eruHuXfkgQAklWT6TsoLIw407sfrzMLYT0cyIMIYRkIpZrg++RARDYfoA4BwkVsDsY1u5pNZ8jolfBSp2RwZpc=
    username: AgB3UIXlbfcy/1TylD8uEDNM1MFUulCh3fvr8mqPrzUL4d6R+ek/Q1tNxdy4AjAsVxhzDfengSiMWpuTfJ++DWik5uyM0Wz+AvOL+I1A1pCu7+LvB0OPpgv05SWPx0wqMLvZdWqfToA+bn3PGlUVW6/vndYxe/zYea2TqGIppeubBzYzKMTh3z4cIJM4j8UPitgsSMRISbEyC0DDZ/Rn790sUWWHiWK5KSQmQyGSdsZnvjqC361tCuxM1MxjEGlDIsHrPGeM6RGqEVSy6tTW3Zw5qEPIviv1Oc5mRzUIeNkfuUPnMkbMwVr6ftrUxH4PG95wb62m3KesIWIOPbK5tJritiO0xBlUeQ50Z7PLsa7RTQ4Xcyjqoifa4wUFUBXTIYGMl2nnHD9f4DCQPR2lcjDmPk8R+ABv860tAe1v386puWA0x8mGpIzdyLvoT102HhxCT6NGFNxtX61paGVHrx5SWHNu7ur8CM3ssBzbYMytLRJtMppsID5yroi7unpO/TvC81z6DobsKigqd00UrGzbRePM81Tk5Zl7rkYK1DtTw1yfKiRH6wB2cSWcs2Ew5XGxV5YmENmczH201qfAbofgr2Ab2S3e32ZIfB+AZeINbR4hfzJK+W0uMGVhwR6Tw+GCWeKfN36mox6jbn6vjAXTSwwialk+9wgZNd18riqAjyjypmmnB0vpk/6K1jlxQ9MzPWKTsA/X
  template:
    metadata:
      name: fs-monitor-idrac
      namespace: mfsm
