---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: default
spec:
  encryptedData:
    admin-password: AgCHUo4X4oWoljgQ8SAxM3D2l1gGtMDZd93Ixn8RlWUACvLk3/AfXtWlJlKdLk8qdduOgJpF62CJ4QZ13EPrnd8uUOyimQKeT82pqRMJufHeCyNJU6r5P7HUtV2ZNuRFBsOBGNM9JzRXmNr05X9CXw79XWMaabt2+328DYhf3vOwDVdU+m0Amd6q6G7zD4+SkITKqEAJwhUfLaw3WujCbijXc+F4qw2X9JDxh9GPCt1rPdS5cEYGIRnMzf/XzYwiQTJZIcbIVRrRB1ScmxasY3kSzhzySj4NJ3JQpu210VzrFeh3Oxy0xe4m79Ng0p5ZUudyZ3fSbL0489wc4TtrOpRIQ9vlDDtUniYGr/NeJhXiqF8tYxv04bZln7EHhURQ6+dyPHtqUnLLx6U6Vb/YCHPuSx+mL5HCoF3sAz6Iu8nOqVhsF5C+5pCSKRV5/MVppqByxfHChEN8leWQl1GZ4uG2V1jpvmaY5tpJOoA7QWln7T4Q2vHlxnLX90oa30TWCnT24bs7O9NbithLLYYLQSYOFtrdaCjuIz2L6MVhRfxbXiMdwKa0OuekiE1JRQASCF/FXNXqANfIL1ucjT51qnz+vriO+7giifhZZ3XfWvRlUFZfArH6jIVHLPL3majmscnuIyZe/2sujOeX3KKMatWPWu2klB1oxyLeJ3eDdtJa4bjNj9/nsXpj+OxOgm4E7kAZO+VMCA8nUvlZSjS7QQ/N+jA0Id22CTbiZ9NXFujtww==
    admin-user: AgDDI4lF3HVKI9cKuiVqy6xhb1T4hmvUEFZtf5qhYOsIDvnsihcuyTRzh7wiBEgRdHrv4SwQpQ/EVO25XMPDkjZ8SubBVBrjk9/bMiUEh7gFBHgxSboyeE2R1pcjTAIOyW66Vr4XThdQ8l26eB2EFUigVMQffu9fq4t1Eq0WUbGTEkCvYdK9o5KDw41Vsz7yADs8RtXVlCq3ir2iRdkaSso0V9jJMcajV20H8ptFi8nyTJf4Yb0e6a5CSzfRo5s8ClNQt+sjXDQ27pe9yZpxQFv1EOFpqsisFWsbr8uHCUByyw0y6cjcw/YegUGM8d1CS8dSmKFp852YlJWQxKxfnR0aL4JNx30lBmsoUej82uDNw6nvMmjOm1FlsHXRFSTd9bnIXYuYBrJxpkzGgE/ClZBa3w6gqSkucaZSSI1EYzcagazZvCE15yqtxuG5hYwrx5D0qrWf/IrWyfdZBoMLFv4IMH4viERtlVqhEfR7fa8o4Dsd5uFHeLVM5Hdv2i7CpObnGOUCUEVWYu3STf9KCPkHrdsxwbuz0NcOKFdqwYgA3z4TpSEE9Dlt74xM4l8HlMcUw4IwJ5tpSpVBpgJlYU8hWrMwdb1ea8SLlO9g/G32kFfmNeK6E6PBvQ3BddQNocr5Uy4y6wq0Oo29jWyCGJO4/B6/ilhE9dZ56j0T9Y9UQMaLPfF7PTRxPOTrWM3ZDLzq44VhXm0=
    ldap-toml: AgBCPfkJTyQh/Y9+TWdaVE0fkU3xUb2gygBH8OfR0ms+YvNGuLvAFv+c+35jRd2cARALf1T961K1JSSbfALkky3J/A5bK5nOqiiUJYEA+uagw7eo6sulXpD0J/8DGerYlZnQokTA7WsbWau3KVZDQsIOl0ocWfnf4FEvRpUr7WUwLAYlLSjTdUcbQz+11pyqZ/olxvBzACZ6t0fA2ZOwA7nW9mnp825rRxsildqoRnp3A6IA+eHtgcBSmXOGRJ5ZpHZgCPYJzmqjH7bYGy/59Jw7T5jg/YygVQzxzfC2vOXIbGIkGm7BqCV9KgNy8xqWwM0rlHRNKS11FkRlBO+Db80uUntEHYXzcyo3vBKdPJEOCCYKZxuohZVsgdeIsIbrWpcTBTKKwGPfJTB7afSNzyKGP8jY4bpowj7NT30mMPCbNs8xf/hiePpIKe/sikkhnz7o7JLTI5CXRRvUfavX5kfb23nAAs6QnFNQ+kNz94H3sDNhvcU5w0OGuXuDDxggg80j5ZjotpKbOU5gplgkMzLluxr+C3CUj0m/4uWKiRYJKCyO5T0k7ydZ+0IyxZuOyIM0/hpXBa75NT5u/IdYFKsKgqxQHpTsj/8pCSzEWzOWlBbGZJfiizvAKbpyAcJUlPPlZhvzZAokksIYQejWeogC+ZwoUVOQ3If3SS+AJmqBb1zghybNhmATG499VUb4ovk=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.0.2
        helm.sh/chart: grafana-9.2.10
      name: monitoring-grafana
      namespace: default
    type: Opaque
