---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  namespace: default
spec:
  encryptedData:
    admin-password: AgCcLuH6Cf8pZFnL9xDKxCAVTqCIcVzeRlrOusL+6qaAR21NEgHVUDT7kqJKW/o64phTWP8kATIpM/HXNhWnuP1b3NmlU64m7s/yCqLBojmcZXnIpprMUw2poE4afXIoxzwmH2o8C9EOOtrxv8AywDvi0YgHJtzR7lORVqwpZP3CLI7HbCbuSbYg/+oCjsPDYgObAUL6rAmUmvxDNL1JLIcJJNU82G3RanbLeEw2WyDD3EFwhD6LdpoCdNUQ0PWvXjYeTiPLUGfOybKmr+uvUy0g0Jl37lP8xZMYIp4tBvYdxznbM+8CNe2klhBFEoP/TMEAGvecLsjwzC7KsV8xx07FPTN3kA1CsUYTLgs2T7M8QQHPyj1/hb6u5wxkikRJ4s14mBujBV1FTyGFBVr7E+7aZzdiqH0GxtsY7DsRvyJ/owl6aqJ+nIyMU+lmSV6kdSKGStZOaCrBgaio+Yj6iJFbTLBQwwKLnJjprW5h3JOzZptFzxH8gwa3Jmbv2XspT+asd7kN9eo2UlilQCPon514y5FSq82NovMeltuqcNFVTYTLE7dD5j442wEuoKgVnM9WOlMWFYuI0EyADkrzDv1XMZr0+sza4iQZgSKR+Cu4GGI5p4IdJUP8fhx+kO9RL7tzOoHaljt91choAfocNih/IBf88kZBKQhh+JhsaNJ7In1FTbIUBbyvVLXQkXVbbZvBSabJss0V8WRyLh55
    admin-user: AgBemiEBaJL1fnlmqORVGwiKC6Zz9MbOhMpPbMSJS7fmzTBhDU1IR55v2NHB76YRDcgTEZDlpPZ+uiAzCc/CjjTSUIe1C+8suMYuAhv6QJbrIrQBlqtvR+I7H/zMr8+dpVhE81DpcTpRRzcSyi8urWDPmaGdT0g3bekeBSNLDcRYS+scPa3H6nKpAOW/yzM0vWHlPxwcUIen5TM12klM2JozRcSlxVxkc7HuGYCpNXvYmzab+aNmb/xZuP5HqMF+181VJIhdiQC6dAxC9L98BT7hEOFyo0p/kSiNPXS6Sr9VwPBqwYM0dRL4TN4Qde8RgOmLSOicSLj2u/ViRjy2k2MmQbdMShFIvV64yleqTMcWbIY7YCy7EQyq8DJm2hvB0IWTXoCED+qlbKDLOHl4MkS9iGfrAha9p8b2dNLKE2W8imc0kF0k2lyQlcV+0iO5QhCkmGm5yswnh0ks3iJdE93eWD8CwT8ayckFUnrC3u5LaDUPUX3aLdCL3X//12ldBNPFdDT1zb8Yu9ZvEoLchUq2gOMUiCxNks8aXIPMheOITjxMEWbdBw1nRL6w40bHaHwoFnvNVftXHvfO/7wogQK5ZXD3ECTO38xNgiWlU4OHpnEbMA4NlNSvH1hPRlxmJfG6agV6PJyyvP/akKu1lo0sWyB4rFeKutKR5sImtwulQ/GbEjsBOdUkOfgdjnxDXDFAJ/yUsQ==
    ldap-toml: AgBCPfkJTyQh/Y9+TWdaVE0fkU3xUb2gygBH8OfR0ms+YvNGuLvAFv+c+35jRd2cARALf1T961K1JSSbfALkky3J/A5bK5nOqiiUJYEA+uagw7eo6sulXpD0J/8DGerYlZnQokTA7WsbWau3KVZDQsIOl0ocWfnf4FEvRpUr7WUwLAYlLSjTdUcbQz+11pyqZ/olxvBzACZ6t0fA2ZOwA7nW9mnp825rRxsildqoRnp3A6IA+eHtgcBSmXOGRJ5ZpHZgCPYJzmqjH7bYGy/59Jw7T5jg/YygVQzxzfC2vOXIbGIkGm7BqCV9KgNy8xqWwM0rlHRNKS11FkRlBO+Db80uUntEHYXzcyo3vBKdPJEOCCYKZxuohZVsgdeIsIbrWpcTBTKKwGPfJTB7afSNzyKGP8jY4bpowj7NT30mMPCbNs8xf/hiePpIKe/sikkhnz7o7JLTI5CXRRvUfavX5kfb23nAAs6QnFNQ+kNz94H3sDNhvcU5w0OGuXuDDxggg80j5ZjotpKbOU5gplgkMzLluxr+C3CUj0m/4uWKiRYJKCyO5T0k7ydZ+0IyxZuOyIM0/hpXBa75NT5u/IdYFKsKgqxQHpTsj/8pCSzEWzOWlBbGZJfiizvAKbpyAcJUlPPlZhvzZAokksIYQejWeogC+ZwoUVOQ3If3SS+AJmqBb1zghybNhmATG499VUb4ovk=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.0.2
        helm.sh/chart: grafana-9.2.10
      name: monitoring-grafana
      namespace: default
    type: Opaque
