apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager/alertmanager.yaml
- alertmanager/secret.yaml
- alertmanager/service.yaml
- alertmanager/serviceaccount.yaml
- alertmanager/servicemonitor.yaml
- crds/crds/crd-alertmanagerconfigs.yaml
- crds/crds/crd-alertmanagers.yaml
- crds/crds/crd-podmonitors.yaml
- crds/crds/crd-probes.yaml
- crds/crds/crd-prometheusagents.yaml
- crds/crds/crd-prometheuses.yaml
- crds/crds/crd-prometheusrules.yaml
- crds/crds/crd-scrapeconfigs.yaml
- crds/crds/crd-servicemonitors.yaml
- crds/crds/crd-thanosrulers.yaml
- exporters/core-dns/service.yaml
- exporters/core-dns/servicemonitor.yaml
- exporters/kube-api-server/servicemonitor.yaml
- exporters/kube-controller-manager/service.yaml
- exporters/kube-controller-manager/servicemonitor.yaml
- exporters/kube-etcd/service.yaml
- exporters/kube-etcd/servicemonitor.yaml
- exporters/kube-proxy/service.yaml
- exporters/kube-proxy/servicemonitor.yaml
- exporters/kube-scheduler/service.yaml
- exporters/kube-scheduler/servicemonitor.yaml
- exporters/kubelet/servicemonitor.yaml
- grafana/certificate.yaml
- grafana/clusterrole.yaml
- grafana/clusterrolebinding.yaml
- grafana/configmap-dashboard-provider.yaml
- grafana/configmap.yaml
- grafana/configmaps-datasources.yaml
- grafana/dashboards-1.14/alertmanager-overview.yaml
- grafana/dashboards-1.14/apiserver.yaml
- grafana/dashboards-1.14/cluster-total.yaml
- grafana/dashboards-1.14/controller-manager.yaml
- grafana/dashboards-1.14/etcd.yaml
- grafana/dashboards-1.14/grafana-overview.yaml
- grafana/dashboards-1.14/k8s-coredns.yaml
- grafana/dashboards-1.14/k8s-resources-cluster.yaml
- grafana/dashboards-1.14/k8s-resources-multicluster.yaml
- grafana/dashboards-1.14/k8s-resources-namespace.yaml
- grafana/dashboards-1.14/k8s-resources-node.yaml
- grafana/dashboards-1.14/k8s-resources-pod.yaml
- grafana/dashboards-1.14/k8s-resources-workload.yaml
- grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
- grafana/dashboards-1.14/kubelet.yaml
- grafana/dashboards-1.14/namespace-by-pod.yaml
- grafana/dashboards-1.14/namespace-by-workload.yaml
- grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
- grafana/dashboards-1.14/node-exporter-full.yaml
- grafana/dashboards-1.14/node-rsrc-use.yaml
- grafana/dashboards-1.14/nodes-aix.yaml
- grafana/dashboards-1.14/nodes-darwin.yaml
- grafana/dashboards-1.14/nodes.yaml
- grafana/dashboards-1.14/persistentvolumesusage.yaml
- grafana/dashboards-1.14/pod-total.yaml
- grafana/dashboards-1.14/prometheus.yaml
- grafana/dashboards-1.14/proxy.yaml
- grafana/dashboards-1.14/scheduler.yaml
- grafana/dashboards-1.14/workload-total.yaml
- grafana/headless-service.yaml
- grafana/ingressroute.yaml
- grafana/role.yaml
- grafana/rolebinding.yaml
- grafana/secret.yaml
- grafana/service.yaml
- grafana/serviceaccount.yaml
- grafana/servicemonitor.yaml
- grafana/statefulset.yaml
- kube-state-metrics/clusterrolebinding.yaml
- kube-state-metrics/deployment.yaml
- kube-state-metrics/role.yaml
- kube-state-metrics/service.yaml
- kube-state-metrics/serviceaccount.yaml
- kube-state-metrics/servicemonitor.yaml
- prometheus/clusterrole.yaml
- prometheus/clusterrolebinding.yaml
- prometheus/prometheus.yaml
- prometheus/rules-1.14/alertmanager.rules.yaml
- prometheus/rules-1.14/config-reloaders.yaml
- prometheus/rules-1.14/etcd.yaml
- prometheus/rules-1.14/general.rules.yaml
- prometheus/rules-1.14/k8s.rules.container_cpu_usage_seconds_total.yaml
- prometheus/rules-1.14/k8s.rules.container_memory_cache.yaml
- prometheus/rules-1.14/k8s.rules.container_memory_rss.yaml
- prometheus/rules-1.14/k8s.rules.container_memory_swap.yaml
- prometheus/rules-1.14/k8s.rules.container_memory_working_set_bytes.yaml
- prometheus/rules-1.14/k8s.rules.container_resource.yaml
- prometheus/rules-1.14/k8s.rules.pod_owner.yaml
- prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
- prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml
- prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml
- prometheus/rules-1.14/kube-apiserver-slos.yaml
- prometheus/rules-1.14/kube-prometheus-general.rules.yaml
- prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
- prometheus/rules-1.14/kube-scheduler.rules.yaml
- prometheus/rules-1.14/kube-state-metrics.yaml
- prometheus/rules-1.14/kubelet.rules.yaml
- prometheus/rules-1.14/kubernetes-apps.yaml
- prometheus/rules-1.14/kubernetes-resources.yaml
- prometheus/rules-1.14/kubernetes-storage.yaml
- prometheus/rules-1.14/kubernetes-system-apiserver.yaml
- prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
- prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml
- prometheus/rules-1.14/kubernetes-system-kubelet.yaml
- prometheus/rules-1.14/kubernetes-system-scheduler.yaml
- prometheus/rules-1.14/kubernetes-system.yaml
- prometheus/rules-1.14/node-exporter.rules.yaml
- prometheus/rules-1.14/node-exporter.yaml
- prometheus/rules-1.14/node-network.yaml
- prometheus/rules-1.14/node.rules.yaml
- prometheus/rules-1.14/prometheus-operator.yaml
- prometheus/rules-1.14/prometheus.yaml
- prometheus/service.yaml
- prometheus/serviceaccount.yaml
- prometheus/servicemonitor.yaml
- prometheus-node-exporter/daemonset.yaml
- prometheus-node-exporter/service.yaml
- prometheus-node-exporter/serviceaccount.yaml
- prometheus-node-exporter/servicemonitor.yaml
- prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
- prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
- prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
- prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
- prometheus-operator/admission-webhooks/job-patch/role.yaml
- prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
- prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
- prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
- prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
- prometheus-operator/clusterrole.yaml
- prometheus-operator/clusterrolebinding.yaml
- prometheus-operator/deployment.yaml
- prometheus-operator/service.yaml
- prometheus-operator/serviceaccount.yaml
- prometheus-operator/servicemonitor.yaml
