apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mtaku3/homelab-manifest.git
        revision: HEAD
        directories:
          - path: dev/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mtaku3/homelab-manifest.git
        targetRevision: HEAD
        path: '{{path}}'
        plugin:
          name: homelab-manifest-build
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ForceConflicts=true
