---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-sso-secret
  namespace: argocd
spec:
  encryptedData:
    client-id: AgAK5VOrcUUN+2mY3W8aMKXmUCX1b34er0yR6yIJg/GLVA7LGvrcs+E5vF23teSid8qItzPnc8nVoYXppNF2nN9t8v9m0WcUFO6I0Z8jXsH+hiipQ5oRUQ/tFTtdNcwWSydfnofC6mRPLdvVWcLBTXVfRF9Tl1xHzANAyqg+ovc14I9oRd7JUx9zi80ciNrmSO3C0mTLe+SABZGt9IkyOv1mr7Sg3KWUyiQcyEfRnzW4vc4t/8BtF3ustDWJc7JVzBmrN1SUSGEQdAG3zqnzGklT7tgOTBtBJtEuPqgaZFHWjly27S31NaU+VMPec0nLX2DfHEnD4JnoBbSfbh/amlQL4lWs+Qh1LzoKiE470nlkE3yZj0is3mUsiEBeKlH0QNBorPwS13iOCy6iyZ/VQHLToTBeA6mZpeq+wjbycB3eFxyp6k6HBZUvqMdXQwEAEwt9VLmaL/aexB4ygzlmbRJ/yzsLImRwZ3Y9kInqSw/8vEydhGJkt7AAydn6+INMBy209Vh4TBHPro9PbArslT8ryVpVh5KjrEwsZ359eRGeZNQ9wS2FzjcuJf5MpukbCGAqiz36MLaosm0oHXQ7XhEJS572EdIxrv8MZKsbxpb28tl13ZLcGtKX9NRQ2BtCUGwQkrnXYRuoqjpilFzOYheq6A7QavQJ0paq013veuLrEwsE6Qdzz3LwA+PkTaBWNtCRfOJ6XIWyK86nMAikl0J0YpORtqIFDxnH0xWbjO2lPOWdfcLSkKqmxQk2G35OW/atAj7SahVKXK6fabwItwWOFQEZQUNtONk=
    client-secret: AgCqOCtqQLjCkRRFdv93Uv1ACtLWaSyed0pKh9J1OidlWIVDSSztc9kw1TSxqBauoJAn3dYIRacl88ymtobOJeWDPLqqwRasTSqfxcppRLAcwkzrla5bMUaqBSvKSuBXjgeBK75Im2pKxIlTfflCjSW7/88OBsalS+3BY1T1UJkaLfnk0p5il334cd+jn+ygX++5ulPfiZLWQ8tAPIV/TNR171aJmQY/duQ7Xx3z8jtPxgxYp1IXBCX3dY1ktCCk+j3uJimxM4vWTgHhp6PEj1ecFEfvecpjYWlNuLPFJU0oS4N63LyZiq7cGpNBgNRbEdctz1cq7YjyaA6EOt8OtqGK0LoibpwwLROhqQWfC7IS0UTXfZtbVv/UipTvBfK3qIrDk/j9sei/7okn1SNYlF4LneI/rbTWly/IM1IG3cZgjY8un5S1QX/YTek8cBNYx6oEMtgOiqu4MlRaMpSB9IIBWVmKLS1gNhkM0k2j314qxa86ZCyEucwrlaljFWMPEbe35rqB8q06Sc5QVLCaL6Co52AuPROJEKh3115GY/uvJkwdYFAhkjxbAMbcrbGZruRrnQ7dL9GdNk/Xqt/fFfm076VQuXTy9WMhf5dzj+1R2rKtJxzpPB/tR8SrWLOZLbzJi+w16Up/ynniHT7xBqmHvbRhgXa5ZXsyZHMYT852EhwnZ5gEGEtarSGwAAk3SRxQsXOw5nyFD1uIV+GUodp4RVFmJh/blGP4Kk6EVILqD2/55g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: google-sso-secret
      namespace: argocd
