---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-sso-secret
  namespace: open-webui
spec:
  encryptedData:
    client-secret: AgA2uuSiHoWsK7HVo5LtbJ4E0w6Z7uxsqYNCTq+wxVCX+rjVrzuNYgT78tl/cTzZcjhwsLty34Fcrux3B2AA5ZyM4JFvQA5/z+JxZkRf+AdwNoQITyrZTGzmzzs5B6kho3i5GZl0VXrUpwsgQ9zrJj3IvxiUYo7K2KBsuhigoWH18YumOVYDNsbd6z1LmLU0SrBe25d4WecxZNV/UkznaT6SBmZOUXoZSyjNkcYWqAu4+/bKWsR0RvW/rBGS7Im9gandskKU51VXZwE2tEfAmjkg+4tgaCHBUtuT0poMstflpvCQHoyeMyKsPIfkbmcktl+H0w76VBhwOLGbmOIAhaLBTMnDwXkMKA/hZ5anstJ4OSlksy0vsolRwAyB5fP5sh2SyY0c7bu4giF8evYoXY0v4FmvmINUKe6FCEwreorbKsZr2oZuVHQYKNQnHgGqhpcZ4JAXMVQ0AZ0lRwf23iapkFTSA9DiXoLf0blpb6GgH70jArzIB08Lc83CPYOYZnc8Wx+02u4T8i8vM2ri7GCsJ/lt6ISfmTQ7Ypf2DwyS7PKsxrPv2FwffjkVqU1JPdwT2Ml9o3zQjPawZxhle8HlD72MgAaO2E1EM0kVCTWvYfUpg7H4lU6cnI0adT4SlGEjY2FRlA8nsnHNlg3uLDZugIBZZqADymtbbwx0CHzrz7e9lSUUnh3n4E5S5XA7wbFh+xXx3VTLtE4Q2f/ZJaRuOa201CoN5fhIjCo/jAkotaAuDQ==
  template:
    metadata:
      name: google-sso-secret
      namespace: open-webui
