---
# Source: loki/templates/loki-canary/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-canary
  namespace: default
  labels:
    helm.sh/chart: loki-6.31.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "3.5.1"
    app.kubernetes.io/component: canary
automountServiceAccountToken: true
