apiVersion: v1
kind: ConfigMap
metadata:
  name: github-sha-plugin
  namespace: argocd
data:
  token: "$github-sha-plugin-secret:plugin-token"
  baseUrl: "http://github-sha-plugin.argocd.svc.cluster.local:4355"
