---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-cloudflare-api-key
  namespace: default
spec:
  encryptedData:
    apiKey: AgBqY3qplR/+g+QUzNC3tBWviSEQ31Eql+cv89Py3tAmNTGqcUddEbKhIGVehv7/kOIj2qELStv3V6FSQiq486ilDQiVJcBEP7iEwpd+GYBS+CZzXG6MfnhP4hm4zDnOgjGkTE5ytlgQhvj5uTSJ0R42betOr15/NWVysCtEtJ2XXhqy6cxEldkJLzqHVuEa+d+xQr3JBaqrwBcPC5Gk7N8tI0cF5x7t+gaGGlsTChRZcuw4SSG0+7qMTo55A4VZEm+3kApEjnLUQL7glp4FiMq1GXz8LY1c58FFru5iMKQQalcNUuifgPofBpU8aZlZ7J7qqTSAhq8LLitABzqliKbmNGCTnnz3C7TnvkGL5QfchqOfV8cuUlXV4tqfb8SZgPrkJg1S2TWasi1GJwIKqg7b/GrZKiT31hM/zqicNMnZMhEyS1xEvSjPmPvCDbscEhZ+BrtF4KLOKIwbmFMDGccjFaVvJWlkuk/MMJS25ZNTSOsZY3aJKTM3aHXgACbdUrClj58IlG0Gq0Y93ziUJt+4sQ2P3ECqxtaGFPrqVN8AsMaPwgDdBqgHfGIB8qzYR4Cm40PwWmvsbStKmFXdm1AIXQWiCI9LnEmbf9lRs5npECpIqjr1dawlHCkEKwySKtUs5ZvjQkdv0NqLq8bkcj1vln3RRYgoyRqf0ONo3O3dsd2hi2IohYIetBDjJrJ5J9R32PXQJ+KpbjNsb7fXyrqYpSz1WFKtDArVBBfmWae45kaSZ8kCEfQJ
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-cloudflare-api-key
      namespace: default
