---
# Source: promtail/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-promtail
  labels:
    helm.sh/chart: promtail-6.17.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "3.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: monitoring
  endpoints:
    - port: http-metrics
      scheme: http
